export type RoutePair = {
  slug: string
  from: string
  to: string
  distance: string
  driveTime: string
  routeDescription: string
  whyBook: string[]
  crossBorder?: boolean
  // Overrides the generated <title>/description in generateMetadata — only
  // set this where the templated copy genuinely underperforms (see the GSC
  // signal audit); leave unset everywhere else so the template stays DRY.
  seoTitle?: string
  seoDescription?: string
}

export const routes: RoutePair[] = [
  {
    slug: 'vienna-airport-to-salzburg',
    from: 'Vienna Airport (VIE)',
    to: 'Salzburg',
    distance: '~300km',
    driveTime: '~2h 45m – 3h',
    routeDescription:
      'The route runs west on the A1 West Autobahn, Austria\'s main east-west corridor, passing Linz before continuing to Salzburg.',
    whyBook: [
      'Avoids a connecting train or a second flight for a same-day arrival',
      'One flat rate regardless of traffic or a delayed landing',
      'Direct to your Salzburg hotel or the Altstadt, no station transfer',
    ],
  },
  {
    slug: 'vienna-airport-to-graz',
    from: 'Vienna Airport (VIE)',
    to: 'Graz',
    distance: '~200km',
    driveTime: '~2h 15m',
    routeDescription:
      'The route follows the A2 Süd Autobahn south through Lower Austria and Styria directly into Graz.',
    whyBook: [
      'One of the more direct airport-to-city runs in Austria',
      'Useful when Graz Airport (GRZ) doesn\'t have a convenient connection from your origin',
      'Fixed price with flight tracking included',
    ],
  },
  {
    slug: 'vienna-to-salzburg',
    from: 'Vienna',
    to: 'Salzburg',
    distance: '~295km',
    driveTime: '~2h 45m',
    routeDescription:
      'A straight run west on the A1 West Autobahn, the same corridor used for the airport route but starting from central Vienna.',
    whyBook: [
      'Faster door-to-door than the train once you factor in getting to and from stations',
      'Room for luggage that doesn\'t suit a train compartment',
      'Depart at the time that works for you, not a fixed timetable',
    ],
  },
  {
    slug: 'vienna-to-graz',
    from: 'Vienna',
    to: 'Graz',
    distance: '~195km',
    driveTime: '~2h',
    routeDescription: 'South on the A2 Süd Autobahn, one of the more scenic Autobahn routes in Austria as it climbs through Lower Austria into Styria.',
    whyBook: [
      'Direct city-center to city-center in about two hours',
      'A common route for business trips between Austria\'s two largest cities',
      'No need to switch to regional transport at either end',
    ],
  },
  {
    slug: 'salzburg-to-innsbruck',
    from: 'Salzburg',
    to: 'Innsbruck',
    distance: '~140–200km',
    driveTime: '~1h 30m – 2h 15m',
    routeDescription:
      'The fastest route briefly crosses into Bavaria on the German A8 Autobahn before re-entering Austria near Kufstein onto the A12 — a shortcut many drivers use. A fully domestic alternative runs via the B178/A12 through Kitzbühel and Wörgl, slightly longer but avoiding the border crossing.',
    whyBook: [
      'We handle the German-Austrian border crossing as part of the fixed price — no separate booking needed',
      'One vehicle the whole way, whichever route is faster on the day',
      'Popular for connecting two of Austria\'s most-visited cities without a flight',
    ],
    crossBorder: true,
  },
  {
    slug: 'linz-to-vienna',
    from: 'Linz',
    to: 'Vienna',
    distance: '~185km',
    driveTime: '~1h 45m – 2h',
    routeDescription: 'East on the A1 West Autobahn, the same corridor used for Vienna–Salzburg traffic, running along the Danube valley for part of the way.',
    whyBook: [
      'A common route for business travel between Upper Austria and the capital',
      'Direct to Vienna Airport as an add-on if you\'re connecting to a flight',
      'Fixed price agreed before you travel',
    ],
  },
  {
    slug: 'vienna-to-bratislava',
    from: 'Vienna',
    to: 'Bratislava',
    distance: '~80km',
    driveTime: '~1h',
    routeDescription:
      'One of the shortest cross-border capital-to-capital drives in Europe, via the A6 motorway through Kittsee to the Slovak border.',
    whyBook: [
      'Fast enough for a same-day round trip',
      'No vehicle switch or paperwork at the border — it\'s handled as part of the service',
      'Popular for business meetings, day trips, and Vienna Airport connections',
    ],
    crossBorder: true,
    seoTitle: 'Vienna to Bratislava Private Transfer | 1 Hour, Fixed Price',
    seoDescription:
      'Private chauffeur transfer from central Vienna to Bratislava — 80km, about an hour, fixed price, no border stop. Ideal for meetings, day trips, and hotel-to-hotel travel.',
  },
  {
    slug: 'vienna-to-budapest',
    from: 'Vienna',
    to: 'Budapest',
    distance: '~245km',
    driveTime: '~2h 30m – 3h',
    routeDescription:
      'Southeast via the A4 Autobahn to the Hungarian border at Hegyeshalom, continuing on the M15/M1 into Budapest.',
    whyBook: [
      'Direct alternative to a connecting flight or train transfer',
      'One licensed driver the whole way, including the border crossing',
      'Comfortable for business trips or weekend travel between the two capitals',
    ],
    crossBorder: true,
  },
  {
    slug: 'salzburg-to-munich',
    from: 'Salzburg',
    to: 'Munich',
    distance: '~145km',
    driveTime: '~1h 30m',
    routeDescription: 'A short cross-border run north on the German A8 Autobahn — one of the most frequently booked international routes from Salzburg.',
    whyBook: [
      'Popular for connecting to Munich Airport (MUC) for onward international flights',
      'No need to book a separate cross-border taxi or transfer service',
      'Fixed price agreed in advance, regardless of border traffic',
    ],
    crossBorder: true,
  },
  {
    slug: 'innsbruck-airport-to-kitzbuehel',
    from: 'Innsbruck Airport (INN)',
    to: 'Kitzbühel',
    distance: '~90km',
    driveTime: '~1h',
    routeDescription: 'East on the A12 Inntal Autobahn before turning onto the B170/B161 into Kitzbühel — the most direct airport-to-resort route in the region.',
    whyBook: [
      'Winter-ready vehicles with space for skis and boards',
      'Direct to your chalet or hotel, no shuttle bus transfer',
      'The shortest airport-to-resort drive time of any major Tyrolean ski town',
    ],
  },
  {
    slug: 'innsbruck-airport-to-st-anton',
    from: 'Innsbruck Airport (INN)',
    to: 'St. Anton am Arlberg',
    distance: '~100km',
    driveTime: '~1h 10m',
    routeDescription: 'West on the A12 Inntal Autobahn and S16 Arlberg Schnellstraße directly into St. Anton.',
    whyBook: [
      'Direct 4x4 luxury transfer to your Arlberg chalet',
      'Spacious vans for ski equipment and large bags',
      'Flight tracking and driver meet & greet inside INN arrival hall',
    ],
  },
  {
    slug: 'innsbruck-airport-to-ischgl',
    from: 'Innsbruck Airport (INN)',
    to: 'Ischgl',
    distance: '~100km',
    driveTime: '~1h 15m',
    routeDescription: 'West via A12 Inntal Autobahn and B188 Silvretta Straße up the Paznaun Valley to Ischgl.',
    whyBook: [
      'Smooth Paznaun Valley transfer with experienced Alpine drivers',
      'Fixed transparent pricing with zero mountain toll surcharges',
      'Luxury Mercedes fleet equipped for winter snow conditions',
    ],
  },
  {
    slug: 'innsbruck-airport-to-soelden',
    from: 'Innsbruck Airport (INN)',
    to: 'Sölden',
    distance: '~85km',
    driveTime: '~1h 10m',
    routeDescription: 'West via A12 to Ötztal exit, then south along the B186 Ötztaler Straße into Sölden.',
    whyBook: [
      'Fastest private transfer from INN to the Ötztal glacier area',
      'Direct delivery to Sölden hotels and 007 Elements base',
      'All-inclusive fixed rate with flight delay monitoring',
    ],
  },
  {
    slug: 'innsbruck-airport-to-mayrhofen',
    from: 'Innsbruck Airport (INN)',
    to: 'Mayrhofen',
    distance: '~75km',
    driveTime: '~1h',
    routeDescription: 'East via A12 Inntal Autobahn, exit Zillertal onto B169 directly to Mayrhofen.',
    whyBook: [
      'Direct Zillertal valley transfer with zero train changes',
      'Winter-equipped vehicles for Hintertux glacier visitors',
      'Personalized pickup right outside Innsbruck arrivals',
    ],
  },
  {
    slug: 'innsbruck-airport-to-lech',
    from: 'Innsbruck Airport (INN)',
    to: 'Lech am Arlberg',
    distance: '~120km',
    driveTime: '~1h 30m',
    routeDescription: 'West via A12 and S16 through the Arlberg Pass or Flexenpass tunnel into Lech.',
    whyBook: [
      'Exclusive VIP transfer service to luxury 5-star Arlberg hotels',
      'Professional chauffeurs trained for heavy winter pass driving',
      'Spacious V-Class and S-Class vehicles available',
    ],
  },
  {
    slug: 'salzburg-airport-to-kitzbuehel',
    from: 'Salzburg Airport (SZG)',
    to: 'Kitzbühel',
    distance: '~75km',
    driveTime: '~1h 15m',
    routeDescription: 'Southwest via Loferer Straße (B178) through Unken and Waidring into Kitzbühel.',
    whyBook: [
      'Popular ski route for charter flights landing at SZG',
      'Comfortable door-to-door service directly to Kitzbühel chalets',
      'No hassle carrying heavy ski bags on regional public transport',
    ],
  },
  {
    slug: 'salzburg-airport-to-zell-am-see',
    from: 'Salzburg Airport (SZG)',
    to: 'Zell am See',
    distance: '~80km',
    driveTime: '~1h 15m',
    routeDescription: 'South via A10 Tauern Autobahn or B311 Pinzgauer Straße to Zell am See.',
    whyBook: [
      'Direct lakefront and Kaprun glacier resort transfer',
      'Fixed rate inclusive of luggage, ski gear, and tolls',
      'Available 24/7 for early morning ski charter arrivals',
    ],
  },
  {
    slug: 'salzburg-airport-to-saalbach',
    from: 'Salzburg Airport (SZG)',
    to: 'Saalbach-Hinterglemm',
    distance: '~85km',
    driveTime: '~1h 20m',
    routeDescription: 'Southwest via B178 and B311 into the Glemmtal valley towards Saalbach.',
    whyBook: [
      'Hassle-free access to the Skicircus ski resort area',
      'Spacious minibuses and Mercedes V-Class for groups & families',
      'Direct drop-off at your hotel door',
    ],
  },
  {
    slug: 'salzburg-airport-to-bad-gastein',
    from: 'Salzburg Airport (SZG)',
    to: 'Bad Gastein',
    distance: '~95km',
    driveTime: '~1h 15m',
    routeDescription: 'South via A10 Tauern Autobahn and B167 up the Gastein Valley to Bad Gastein.',
    whyBook: [
      'Scenic valley drive straight to historic Belle Époque spa hotels',
      'Comfortable ride for winter ski and summer wellness guests',
      'Fixed transparent price with flight delay tracking included',
    ],
  },
  {
    slug: 'munich-airport-to-innsbruck',
    from: 'Munich Airport (MUC)',
    to: 'Innsbruck',
    distance: '~160km',
    driveTime: '~2h',
    routeDescription: 'South via German A9 and A8 Autobahns, crossing into Austria via A93/A12 Inntal Autobahn to Innsbruck.',
    whyBook: [
      'Seamless cross-border transfer from Germany’s top long-haul hub',
      'No train changes with heavy luggage at Munich Central Station',
      'Licensed cross-border chauffeurs with fixed pricing',
    ],
    crossBorder: true,
  },
  {
    slug: 'munich-airport-to-salzburg',
    from: 'Munich Airport (MUC)',
    to: 'Salzburg',
    distance: '~170km',
    driveTime: '~1h 45m',
    routeDescription: 'East via German A92 and A8 Autobahn, crossing the Austrian border at Walserberg directly to Salzburg.',
    whyBook: [
      'Direct link between MUC long-haul flights and Salzburg Altstadt',
      'Avoids German railway delays or rental car drop-off fees',
      'Professional meet & greet service in MUC Terminal 1 or 2',
    ],
    crossBorder: true,
  },
  {
    slug: 'munich-airport-to-kitzbuehel',
    from: 'Munich Airport (MUC)',
    to: 'Kitzbühel',
    distance: '~165km',
    driveTime: '~2h',
    routeDescription: 'South via A8 towards Inntal Dreieck, continuing via A93/B173 through Kufstein to Kitzbühel.',
    whyBook: [
      'Top choice for international long-haul travelers heading to Kitzbühel',
      '4x4 vehicles equipped for winter snow conditions across Bavaria/Tyrol',
      'One vehicle and driver door-to-door without border delays',
    ],
    crossBorder: true,
  },
  {
    slug: 'munich-airport-to-st-anton',
    from: 'Munich Airport (MUC)',
    to: 'St. Anton am Arlberg',
    distance: '~240km',
    driveTime: '~2h 45m',
    routeDescription: 'South via A95 or A8/A12 through the Inntal valley to Arlberg.',
    whyBook: [
      'Direct executive transfer for overseas visitors arriving in Munich',
      'Spacious V-Class and SUV fleet for ski luggage',
      'All border toll vignettes and fees included in fixed fare',
    ],
    crossBorder: true,
  },
  {
    slug: 'zurich-airport-to-lech',
    from: 'Zurich Airport (ZRH)',
    to: 'Lech am Arlberg',
    distance: '~195km',
    driveTime: '~2h 15m',
    routeDescription: 'East via Swiss A1/A3 motorways, past Lake Walen, entering Austria near Feldkirch to Lech.',
    whyBook: [
      'The premier luxury transfer route from Zurich to Arlberg 5-star resorts',
      'Licensed for Swiss-Austrian international chauffeur transfers',
      'Discreet executive service for high-net-worth travelers',
    ],
    crossBorder: true,
  },
  {
    slug: 'zurich-airport-to-st-anton',
    from: 'Zurich Airport (ZRH)',
    to: 'St. Anton am Arlberg',
    distance: '~200km',
    driveTime: '~2h 15m',
    routeDescription: 'East across Switzerland via A3/A13, entering Vorarlberg/Tyrol via Arlberg Pass or tunnel.',
    whyBook: [
      'Preferred route for international arrivals via Zurich Kloten',
      'Spacious luxury Mercedes vans for families and ski equipment',
      'Fixed cross-border pricing with zero surprise charges',
    ],
    crossBorder: true,
  },
  {
    slug: 'vienna-airport-to-bratislava',
    from: 'Vienna Airport (VIE)',
    to: 'Bratislava',
    distance: '~65km',
    driveTime: '~45m',
    routeDescription: 'East via A4 and A6 motorways through Kittsee across the border to Bratislava — booked in either direction, arrival or departure.',
    whyBook: [
      'Shortest capital-to-capital transfer in Central Europe',
      'Covers both directions — VIE arrivals heading into Slovakia, and Bratislava departures connecting to a flight at Vienna Airport',
      'Fast, direct, and fixed price door-to-door',
    ],
    crossBorder: true,
    seoTitle: 'Vienna Airport to Bratislava Transfer | 45 Minutes, Fixed Price',
    seoDescription:
      'Private transfer between Vienna Airport and Bratislava — 65km, ~45 minutes, fixed price door-to-door. Covers both arrivals into VIE and departures from Bratislava.',
  },
  {
    slug: 'vienna-airport-to-budapest',
    from: 'Vienna Airport (VIE)',
    to: 'Budapest',
    distance: '~230km',
    driveTime: '~2h 15m',
    routeDescription: 'Southeast via A4 Autobahn and Hungarian M1 motorway directly to Budapest.',
    whyBook: [
      'High-demand long-distance airport-to-capital transfer',
      'Avoids airport transit connections or train station transfers',
      'Professional bilingual driver comfortable with international routes',
    ],
    crossBorder: true,
  },
  {
    slug: 'vienna-airport-to-hallstatt',
    from: 'Vienna Airport (VIE)',
    to: 'Hallstatt',
    distance: '~300km',
    driveTime: '~3h 15m',
    routeDescription: 'West via A1 West Autobahn to Regau exit, continuing through Gmunden & Bad Ischl to Hallstatt.',
    whyBook: [
      'Direct luxury tour/transfer from Vienna Airport to UNESCO Hallstatt',
      'No complicated multi-leg train and ferry connections with luggage',
      'Option to add scenic stops in the Salzkammergut region',
    ],
  },
  {
    slug: 'salzburg-to-hallstatt',
    from: 'Salzburg',
    to: 'Hallstatt',
    distance: '~75km',
    driveTime: '~1h 15m',
    routeDescription: 'East via B158 Wolfgangsee Straße through Fuschl and St. Gilgen, then B145 to Hallstatt.',
    whyBook: [
      'Most popular day trip and private transfer route from Salzburg',
      'Stunning scenic drive through Lake Fuschl and Wolfgangsee',
      'Flexible departure times tailored to your itinerary',
    ],
  },
  {
    slug: 'salzburg-airport-to-schladming',
    from: 'Salzburg Airport (SZG)',
    to: 'Schladming',
    distance: '~90km',
    driveTime: '~1h',
    routeDescription: 'South via A10 Tauern Autobahn and B320 Ennstal Straße directly to Schladming.',
    whyBook: [
      'Fastest gateway access to Planai and Ski Amadé 4-Mountain area',
      'Fixed rate including Tauern motorway toll fees',
      'Direct hotel drop-off without carrying ski gear on public trains',
    ],
  },
  {
    slug: 'salzburg-airport-to-obertauern',
    from: 'Salzburg Airport (SZG)',
    to: 'Obertauern',
    distance: '~90km',
    driveTime: '~1h 10m',
    routeDescription: 'South via A10 Tauern Autobahn to Radstadt exit, up B99 Radstädter Tauern Straße to Obertauern.',
    whyBook: [
      'Direct transfer to snow-sure high altitude pass resort',
      '4x4 luxury vehicles experienced in heavy winter mountain driving',
      'All-inclusive fixed price with flight delay monitoring',
    ],
  },
  {
    slug: 'munich-airport-to-saalbach',
    from: 'Munich Airport (MUC)',
    to: 'Saalbach-Hinterglemm',
    distance: '~215km',
    driveTime: '~2h 30m',
    routeDescription: 'South via German A8, crossing into Austria via Siegsdorf/Lofer (B178) into Glemmtal.',
    whyBook: [
      'Popular international long-haul transfer for UK and Scandinavian skiers',
      'Large Mercedes V-Class vans for groups with heavy ski baggage',
      'No border hassle or highway vignette worries',
    ],
    crossBorder: true,
  },
  {
    slug: 'munich-airport-to-zell-am-see',
    from: 'Munich Airport (MUC)',
    to: 'Zell am See',
    distance: '~200km',
    driveTime: '~2h 15m',
    routeDescription: 'South via A8 motorway and B311 Pinzgauer Straße directly to Lake Zell.',
    whyBook: [
      'Direct transfers for long-haul MUC arrivals heading to Zell & Kaprun glacier',
      'Fixed transparent price agreed in advance',
      'Full flight tracking and arrivals hall meet-and-greet',
    ],
    crossBorder: true,
  },
  {
    slug: 'munich-airport-to-mayrhofen',
    from: 'Munich Airport (MUC)',
    to: 'Mayrhofen',
    distance: '~190km',
    driveTime: '~2h 15m',
    routeDescription: 'South via A8 and A93/A12 Inntal corridor, exit Zillertal (B169) into Mayrhofen.',
    whyBook: [
      'Direct luxury chauffeur transfer from MUC straight to Zillertal valley',
      'Spacious vans accommodating glacier ski gear',
      'Comfortable door-to-door journey avoiding crowded Munich trains',
    ],
    crossBorder: true,
  },
  {
    slug: 'munich-airport-to-soelden',
    from: 'Munich Airport (MUC)',
    to: 'Sölden',
    distance: '~240km',
    driveTime: '~2h 45m',
    routeDescription: 'South via German Autobahn network and A12/B186 into the Ötztal valley.',
    whyBook: [
      'Reliable cross-border transfer for long-haul international visitors',
      'All toll fees and vignettes included in fixed quote',
      '4x4 Mercedes vehicles tailored for Alpine snow roads',
    ],
    crossBorder: true,
  },
  {
    slug: 'zurich-airport-to-ischgl',
    from: 'Zurich Airport (ZRH)',
    to: 'Ischgl',
    distance: '~235km',
    driveTime: '~2h 30m',
    routeDescription: 'East across Swiss motorways A3/A13, entering Austria at Feldkirch onto S16/B188 Paznaun.',
    whyBook: [
      'High-end VIP cross-border transfer service for Zurich arrivals',
      'Experienced Swiss-Austrian cross-border chauffeurs',
      'Discreet and comfortable executive travel',
    ],
    crossBorder: true,
  },
  {
    slug: 'graz-to-ljubljana',
    from: 'Graz',
    to: 'Ljubljana',
    distance: '~195km',
    driveTime: '~2h',
    routeDescription: 'South via the A2 Süd Autobahn through the Spielfeld border crossing into Slovenia onto the A1 motorway.',
    whyBook: [
      'Seamless regional cross-border connection between Styria and Slovenia',
      'Ideal for business trips and diplomatic travel',
      'Fixed rate with Slovenian highway vignette included',
    ],
    crossBorder: true,
  },
  {
    slug: 'graz-to-venice',
    from: 'Graz',
    to: 'Venice',
    distance: '~380km',
    driveTime: '~3h 45m',
    routeDescription: 'Southwest via A2 Süd Autobahn, crossing Tarvisio border into Italy on A23/A4 to Venice.',
    whyBook: [
      'Exclusive private intercity transfer to the Venetian lagoon (Piazzale Roma)',
      'Comfortable long-distance Mercedes sedan or van ride',
      'Flexible stops along the route in Carinthia or Friuli',
    ],
    crossBorder: true,
  },
  {
    slug: 'klagenfurt-to-ljubljana',
    from: 'Klagenfurt',
    to: 'Ljubljana',
    distance: '~85km',
    driveTime: '~1h',
    routeDescription: 'South via B91 Loiblpass or A11 Karawankentunnel directly into Slovenia.',
    whyBook: [
      'Fastest cross-border transfer between Carinthia and Ljubljana',
      'Karawankentunnel toll fees included in fixed quote',
      'Door-to-door hotel and business transfer',
    ],
    crossBorder: true,
  },
  {
    slug: 'klagenfurt-to-venice',
    from: 'Klagenfurt',
    to: 'Venice',
    distance: '~280km',
    driveTime: '~2h 45m',
    routeDescription: 'Southwest via A2 Süd Autobahn across the Italian border via Udine (A23) to Venice.',
    whyBook: [
      'Direct Alpine-to-Adriatic luxury chauffeur transfer',
      'No train transfers carrying heavy cruise or holiday luggage',
      'Licensed for international Italian pickups and drop-offs',
    ],
    crossBorder: true,
  },
  {
    slug: 'vienna-to-prague',
    from: 'Vienna',
    to: 'Prague',
    distance: '~310km',
    driveTime: '~3h 15m',
    routeDescription: 'North via A5 Weinviertel Autobahn into Czech Republic via Mikulov on D52/D1 to Prague.',
    whyBook: [
      'Top-tier capital-to-capital private transfer in Central Europe',
      'Direct pick-up from Vienna hotels to Prague Castle or Old Town',
      'All Czech highway vignette fees included',
    ],
    crossBorder: true,
  },
  {
    slug: 'salzburg-to-graz',
    from: 'Salzburg',
    to: 'Graz',
    distance: '~280km',
    driveTime: '~2h 45m',
    routeDescription: 'Southeast via A10 Tauern Autobahn and A9 Pyhrn Autobahn through Ennstal valley.',
    whyBook: [
      'Connects Austria’s premier festival city with Styria’s capital',
      'Comfortable intercity transfer avoiding regional train connections',
      'Fixed pricing with mountain tunnel tolls included',
    ],
  },
  {
    slug: 'bregenz-to-zurich-airport',
    from: 'Bregenz',
    to: 'Zurich Airport (ZRH)',
    distance: '~120km',
    driveTime: '~1h 15m',
    routeDescription: 'West across the Swiss border (Höchst/St. Margrethen) via Swiss A1 motorway to Zurich Kloten.',
    whyBook: [
      'Primary airport connection for Vorarlberg residents and businesses',
      'Cross-border licensed driver with Swiss vignette included',
      'Punctual airport transfers with flight tracking',
    ],
    crossBorder: true,
  },
  {
    slug: 'innsbruck-to-zurich',
    from: 'Innsbruck',
    to: 'Zurich',
    distance: '~290km',
    driveTime: '~3h',
    routeDescription: 'West via A12/S16 through Arlberg, crossing Liechtenstein/Switzerland border on A3 to Zurich.',
    whyBook: [
      'Direct city-to-city transfer connecting Tyrol with Zurich financial district',
      'Comfortable executive ride with optional stops in Vaduz or Bregenz',
      'Fixed rate covering all international transit fees',
    ],
    crossBorder: true,
  },
  {
    slug: 'vienna-to-wachau',
    from: 'Vienna',
    to: 'Wachau Valley',
    distance: '~85km',
    driveTime: '~1h',
    routeDescription: 'West along A1 and S33 to Krems and the scenic Danube wine valley (Dürnstein/Melk).',
    whyBook: [
      'Private day-tour and wine tasting transfer with a dedicated driver',
      'Flexible itinerary with stops at Melk Abbey and vineyards',
      'Fixed daily or transfer pricing',
    ],
  },
  {
    slug: 'vienna-to-baden-wien',
    from: 'Vienna',
    to: 'Baden bei Wien',
    distance: '~30km',
    driveTime: '~35m',
    routeDescription: 'South via A2 Süd Autobahn directly into the spa town of Baden.',
    whyBook: [
      'Quick executive transfer to Baden Thermal Spa and Casino',
      'Ideal for hotel guests, evening casino visits, and wellness retreats',
      'Fixed price door-to-door',
    ],
  },
  {
    slug: 'bregenz-to-lech',
    from: 'Bregenz',
    to: 'Lech am Arlberg',
    distance: '~95km',
    driveTime: '~1h 15m',
    routeDescription: 'Southeast via Rheintal Autobahn A14 and B197 up the Flexenpass to Lech.',
    whyBook: [
      'Direct Vorarlberg valley connection to luxury Arlberg resort',
      'Experienced mountain chauffeurs for heavy winter snowfall',
      'Spacious V-Class luxury vans for families and ski gear',
    ],
  },
  {
    slug: 'bregenz-to-st-anton',
    from: 'Bregenz',
    to: 'St. Anton am Arlberg',
    distance: '~105km',
    driveTime: '~1h 20m',
    routeDescription: 'Southeast via A14 and S16 Arlberg Schnellstraße to St. Anton.',
    whyBook: [
      'Fast, direct transfer connecting Lake Constance with the Arlberg ski area',
      'All mountain tunnel tolls included',
      'Fixed rate with professional chauffeur',
    ],
  },
  {
    slug: 'linz-to-salzburg',
    from: 'Linz',
    to: 'Salzburg',
    distance: '~130km',
    driveTime: '~1h 25m',
    routeDescription: 'West via A1 West Autobahn connecting Upper Austria with Salzburg state.',
    whyBook: [
      'Frequent intercity transfer for business and leisure travelers',
      'Avoids train station transfers with heavy luggage',
      'Direct hotel or Linz/Salzburg airport connection',
    ],
  },
  {
    slug: 'villach-to-venice',
    from: 'Villach',
    to: 'Venice',
    distance: '~240km',
    driveTime: '~2h 30m',
    routeDescription: 'Southwest via A2 Süd Autobahn across Tarvisio Italian border via Udine (A23/A4) to Venice.',
    whyBook: [
      'Shortest luxury cross-border drive from Carinthia to the Venetian coast',
      'Direct drop-off at Piazzale Roma or Venice cruise port terminal',
      'Licensed for international Italian pickups and drop-offs',
    ],
    crossBorder: true,
  },
  {
    slug: 'villach-to-ljubljana',
    from: 'Villach',
    to: 'Ljubljana',
    distance: '~100km',
    driveTime: '~1h',
    routeDescription: 'South via A11 Karawankentunnel directly into Slovenia to Ljubljana.',
    whyBook: [
      'Fastest cross-border connection between Carinthia and Ljubljana Airport/City',
      'Tunnel tolls and Slovenian highway vignette included',
      '24/7 private transfer availability',
    ],
    crossBorder: true,
  },
  {
    slug: 'salzburg-airport-to-berchtesgaden',
    from: 'Salzburg Airport (SZG)',
    to: 'Berchtesgaden',
    distance: '~30km',
    driveTime: '~35m',
    routeDescription:
      'A short cross-border run southwest on the B305/B20, crossing into Bavaria near Hangender Stein and continuing directly into Berchtesgaden.',
    whyBook: [
      'One of the shortest airport transfers on the network, ideal for a same-day Eagle\'s Nest or Königssee visit',
      'No rental car or local bus connections needed for a day trip across the border',
      'Fixed price with the border crossing included',
    ],
    crossBorder: true,
  },
  {
    slug: 'salzburg-airport-to-hallstatt',
    from: 'Salzburg Airport (SZG)',
    to: 'Hallstatt',
    distance: '~75km',
    driveTime: '~1h 15m',
    routeDescription:
      'South via the B158 Wolfgangsee Straße through Fuschl and St. Gilgen, then the B145 into Hallstatt — the same scenic Salzkammergut route used from central Salzburg.',
    whyBook: [
      'Direct from arrivals to the UNESCO lakeside village, no connecting train or bus into central Salzburg first',
      'Useful for guests flying in for a single-day Hallstatt visit before continuing elsewhere',
      'Fixed price with flight tracking included',
    ],
  },
  {
    slug: 'vienna-airport-to-linz',
    from: 'Vienna Airport (VIE)',
    to: 'Linz',
    distance: '~185km',
    driveTime: '~1h 45m – 2h',
    routeDescription:
      'West on the A1 West Autobahn along the Danube corridor, the same route used for Vienna–Salzburg traffic but ending in Linz.',
    whyBook: [
      'Avoids a train transfer through Vienna\'s main station with luggage',
      'Useful when Linz Airport doesn\'t have a convenient connection from your origin',
      'Fixed price agreed before you travel',
    ],
  },
  {
    slug: 'vienna-airport-to-wachau',
    from: 'Vienna Airport (VIE)',
    to: 'Wachau Valley',
    distance: '~100km',
    driveTime: '~1h 10m',
    routeDescription:
      'West via the A1 and S33 to Krems, at the eastern edge of the Danube wine valley — the same corridor used for the Vienna–Wachau city route.',
    whyBook: [
      'Direct from arrivals to a Wachau hotel or vineyard, skipping a transfer through central Vienna',
      'Useful for wine-tourism arrivals heading straight to Dürnstein or Krems',
      'Flexible stops available on request',
    ],
  },
  {
    slug: 'vienna-airport-to-baden-wien',
    from: 'Vienna Airport (VIE)',
    to: 'Baden bei Wien',
    distance: '~40km',
    driveTime: '~35m',
    routeDescription:
      'South via the A4 and A2 Süd Autobahn, bypassing central Vienna, directly into the spa town of Baden.',
    whyBook: [
      'Quick, direct arrival transfer to Baden\'s thermal spas and casino',
      'Skips a train-plus-taxi connection through Vienna Meidling',
      'Fixed price door to door',
    ],
  },
  {
    slug: 'salzburg-airport-to-innsbruck',
    from: 'Salzburg Airport (SZG)',
    to: 'Innsbruck',
    distance: '~140–200km',
    driveTime: '~1h 45m – 2h 15m',
    routeDescription:
      'The fastest route briefly crosses into Bavaria via the German A8 before rejoining the A12 near Kufstein — the same shortcut used on the Salzburg–Innsbruck city route.',
    whyBook: [
      'One vehicle the whole way, including the short German border crossing',
      'Avoids a domestic connecting flight between the two cities',
      'Popular for cross-region arrivals heading straight to Tyrol',
    ],
    crossBorder: true,
  },
  {
    slug: 'salzburg-airport-to-munich',
    from: 'Salzburg Airport (SZG)',
    to: 'Munich',
    distance: '~145km',
    driveTime: '~1h 30m',
    routeDescription:
      'North via the German A8 Autobahn — a short cross-border run for travelers connecting onward through Munich Airport or heading into the city.',
    whyBook: [
      'Popular for onward international connections via MUC',
      'Avoids booking a separate cross-border taxi from Salzburg',
      'Fixed price agreed in advance, regardless of border traffic',
    ],
    crossBorder: true,
  },
  {
    slug: 'innsbruck-airport-to-seefeld',
    from: 'Innsbruck Airport (INN)',
    to: 'Seefeld in Tirol',
    distance: '~25km',
    driveTime: '~25m',
    routeDescription:
      'North via the B177 Zirler Berg road, climbing out of the Inn Valley onto the Seefeld plateau — one of the shortest airport-to-resort drives in Austria.',
    whyBook: [
      'The shortest airport transfer of any major Tyrolean resort',
      'Direct to Seefeld\'s hotels, avoiding the regional train and a village shuttle',
      'Well suited to the car-free village\'s pedestrian center',
    ],
  },
  {
    slug: 'innsbruck-airport-to-serfaus-fiss-ladis',
    from: 'Innsbruck Airport (INN)',
    to: 'Serfaus-Fiss-Ladis',
    distance: '~85km',
    driveTime: '~1h 15m',
    routeDescription:
      'West via the A12 Inntal Autobahn towards Landeck, then south into the Serfaus-Fiss-Ladis plateau above the valley.',
    whyBook: [
      'Direct to the plateau villages, skipping the local cable-car connection some travelers use from the valley floor',
      'Family-oriented resort with space for larger groups\' luggage and equipment',
      'Fixed transparent price agreed before travel',
    ],
  },
  {
    slug: 'linz-airport-to-hallstatt',
    from: 'Linz Airport (LNZ)',
    to: 'Hallstatt',
    distance: '~80km',
    driveTime: '~1h 15m',
    routeDescription: 'South via the A1 and B145 through the Salzkammergut lake district into Hallstatt.',
    whyBook: [
      'Direct from arrivals to the UNESCO village, no multi-leg train and ferry connection with luggage',
      'Useful for travelers using Linz as a quieter alternative to Salzburg or Vienna airports',
      'Fixed price with flight tracking included',
    ],
  },
  {
    slug: 'klagenfurt-airport-to-villach',
    from: 'Klagenfurt Airport (KLU)',
    to: 'Villach',
    distance: '~40km',
    driveTime: '~30m',
    routeDescription: 'West on the A2 Süd Autobahn, a short and direct run across the Carinthian lake district.',
    whyBook: [
      'Short, high-frequency transfer between Carinthia\'s two largest towns',
      'Useful as a connector before onward travel to Italy or Slovenia',
      'Fixed price door to door',
    ],
  },
  {
    slug: 'vienna-to-hallstatt',
    from: 'Vienna',
    to: 'Hallstatt',
    distance: '~280km',
    driveTime: '~3h',
    routeDescription: 'West on the A1 West Autobahn to the Salzkammergut, then south via the B145 through Bad Ischl into Hallstatt.',
    whyBook: [
      'A long but popular day-trip route for international visitors based in Vienna',
      'One vehicle door to door, avoiding the train-plus-ferry connection to the village',
      'Flexible stops available in Bad Ischl or along the lake district',
    ],
  },
  {
    slug: 'salzburg-to-zell-am-see',
    from: 'Salzburg',
    to: 'Zell am See',
    distance: '~90km',
    driveTime: '~1h',
    routeDescription: 'South via the A10 Tauern Autobahn or the B311 Pinzgauer Straße directly to the Zeller See lakefront.',
    whyBook: [
      'Popular weekend route for both winter skiing and summer lake travel',
      'Direct to lakefront hotels, no regional train transfer',
      'Fixed price including motorway tolls',
    ],
  },
  {
    slug: 'salzburg-to-kitzbuehel',
    from: 'Salzburg',
    to: 'Kitzbühel',
    distance: '~95km',
    driveTime: '~1h 15m',
    routeDescription:
      'Southwest via the B178 Loferer Straße through Unken and Waidring into Kitzbühel — the same corridor used from Salzburg Airport.',
    whyBook: [
      'Direct city-to-resort transfer without a station change',
      'Comfortable for groups traveling with ski or golf equipment',
      'Fixed price agreed before travel',
    ],
  },
  {
    slug: 'innsbruck-to-kitzbuehel',
    from: 'Innsbruck',
    to: 'Kitzbühel',
    distance: '~90km',
    driveTime: '~1h',
    routeDescription:
      'East on the A12 Inntal Autobahn before turning onto the B170/B161 into Kitzbühel, the same route used from Innsbruck Airport.',
    whyBook: [
      'Direct city-to-resort connection across Tyrol',
      'No shuttle bus or regional train changes with ski luggage',
      'Fixed rate regardless of traffic',
    ],
  },
  {
    slug: 'innsbruck-to-st-anton',
    from: 'Innsbruck',
    to: 'St. Anton am Arlberg',
    distance: '~105km',
    driveTime: '~1h 15m',
    routeDescription: 'West via the A12 Inntal Autobahn and the S16 Arlberg Schnellstraße directly into St. Anton.',
    whyBook: [
      'Direct city-to-resort transfer through the Arlberg tunnel',
      'Spacious vehicles for ski equipment and multi-day luggage',
      'Fixed price agreed before travel',
    ],
  },
  {
    slug: 'innsbruck-to-mayrhofen',
    from: 'Innsbruck',
    to: 'Mayrhofen',
    distance: '~75km',
    driveTime: '~1h',
    routeDescription: 'East via the A12 Inntal Autobahn, exiting onto the B169 into the Zillertal valley and Mayrhofen.',
    whyBook: [
      'Direct Zillertal valley transfer without a regional train change at Jenbach',
      'Popular for weekend and week-long ski trips from Innsbruck',
      'Fixed price including motorway tolls',
    ],
  },
  {
    slug: 'innsbruck-to-munich',
    from: 'Innsbruck',
    to: 'Munich',
    distance: '~165km',
    driveTime: '~2h',
    routeDescription: 'North via the A12/A93 Inntal corridor, crossing into Germany near Kufstein onto the A8 to Munich.',
    whyBook: [
      'One vehicle the whole way, including the German border crossing',
      'Popular for onward international connections through Munich Airport',
      'Fixed price agreed before travel, regardless of border traffic',
    ],
    crossBorder: true,
  },
  {
    slug: 'innsbruck-to-bolzano',
    from: 'Innsbruck',
    to: 'Bolzano',
    distance: '~210km',
    driveTime: '~2h 15m',
    routeDescription:
      'South via the A13 Brenner Autobahn, Austria\'s main route into Italy, crossing the Brenner Pass into South Tyrol.',
    whyBook: [
      'The Brenner Pass crossing is handled as part of the fixed price, including the Italian vignette',
      'Comfortable for business travel or a scenic Dolomites trip',
      'One driver and vehicle the whole way, no station transfer in Bolzano',
    ],
    crossBorder: true,
  },
  {
    slug: 'linz-to-prague',
    from: 'Linz',
    to: 'Prague',
    distance: '~215km',
    driveTime: '~2h 30m',
    routeDescription: 'North via the A7 Mühlkreis Autobahn, crossing into the Czech Republic near Wullowitz onto the D3 towards Prague.',
    whyBook: [
      'Direct capital connection avoiding a regional train transfer through Linz Hauptbahnhof',
      'One licensed driver for the whole cross-border journey',
      'Fixed price agreed in advance',
    ],
    crossBorder: true,
  },
  {
    slug: 'reutte-to-fuessen',
    from: 'Reutte',
    to: 'Füssen',
    distance: '~25km',
    driveTime: '~25m',
    routeDescription: 'A short cross-border hop on the B179, crossing into Bavaria just north of Reutte into Füssen.',
    whyBook: [
      'The most direct way to reach Neuschwanstein and Hohenschwangau castles from the Tyrolean side',
      'No local bus timetable to work around for a same-day castle visit',
      'Fixed price with the border crossing included',
    ],
    crossBorder: true,
  },
  {
    slug: 'vienna-airport-to-eisenstadt',
    from: 'Vienna Airport (VIE)',
    to: 'Eisenstadt',
    distance: '~60km',
    driveTime: '~50m',
    routeDescription: 'South via the A6 and B50, a short run through Burgenland\'s vineyards into the state capital.',
    whyBook: [
      'Direct arrival transfer for business travel or Burgenland wine tourism',
      'Avoids a regional bus connection from Vienna',
      'Fixed price agreed before you travel',
    ],
  },
  {
    slug: 'vienna-airport-to-st-poelten',
    from: 'Vienna Airport (VIE)',
    to: 'St. Pölten',
    distance: '~75km',
    driveTime: '~1h',
    routeDescription: 'West via the A1 West Autobahn, bypassing central Vienna, directly into Lower Austria\'s state capital.',
    whyBook: [
      'Useful for government and business travel without a Vienna train transfer',
      'Direct to St. Pölten offices or hotels',
      'Fixed price regardless of traffic',
    ],
  },
  {
    slug: 'vienna-airport-to-wiener-neustadt',
    from: 'Vienna Airport (VIE)',
    to: 'Wiener Neustadt',
    distance: '~45km',
    driveTime: '~40m',
    routeDescription: 'South via the A4 and S6, a short run into Lower Austria\'s second-largest city.',
    whyBook: [
      'Quick, direct transfer for business travel south of Vienna',
      'No regional train changes with luggage',
      'Fixed price door to door',
    ],
  },
  {
    slug: 'vienna-airport-to-sopron',
    from: 'Vienna Airport (VIE)',
    to: 'Sopron',
    distance: '~90km',
    driveTime: '~1h',
    routeDescription: 'Southeast via the A4 Autobahn, crossing into Hungary near Klingenbach into Sopron.',
    whyBook: [
      'One vehicle for the whole cross-border journey, including the Hungarian border',
      'Popular for spa and wine tourism just across the border',
      'Fixed price agreed in advance',
    ],
    crossBorder: true,
  },
  {
    slug: 'vienna-airport-to-prague',
    from: 'Vienna Airport (VIE)',
    to: 'Prague',
    distance: '~330km',
    driveTime: '~3h 15m',
    routeDescription:
      'North via the A5 Weinviertel Autobahn into the Czech Republic via Mikulov, continuing on the D52/D1 to Prague.',
    whyBook: [
      'Direct alternative to a connecting flight for VIE arrivals heading to Prague',
      'One licensed driver the whole cross-border journey',
      'Fixed price agreed in advance',
    ],
    crossBorder: true,
  },
  {
    slug: 'salzburg-airport-to-bad-ischl',
    from: 'Salzburg Airport (SZG)',
    to: 'Bad Ischl',
    distance: '~55km',
    driveTime: '~50m',
    routeDescription: 'East via the B158 Wolfgangsee Straße through Fuschl and St. Gilgen into the Salzkammergut spa town of Bad Ischl.',
    whyBook: [
      'Direct arrival transfer for Salzkammergut spa and lake-district visitors',
      'Avoids a regional bus connection from Salzburg',
      'Fixed price with flight tracking included',
    ],
  },
  {
    slug: 'innsbruck-airport-to-garmisch',
    from: 'Innsbruck Airport (INN)',
    to: 'Garmisch-Partenkirchen',
    distance: '~65km',
    driveTime: '~1h',
    routeDescription: 'North via the B171 and B2, crossing into Bavaria near Scharnitz into Garmisch-Partenkirchen.',
    whyBook: [
      'One vehicle for the whole cross-border journey, including the German border crossing',
      'Popular for Zugspitze day trips and winter sports visitors',
      'Fixed price agreed in advance',
    ],
    crossBorder: true,
  },
  {
    slug: 'innsbruck-airport-to-bolzano',
    from: 'Innsbruck Airport (INN)',
    to: 'Bolzano',
    distance: '~210km',
    driveTime: '~2h 15m',
    routeDescription:
      'South via the A13 Brenner Autobahn, Austria\'s main route into Italy, crossing the Brenner Pass into South Tyrol.',
    whyBook: [
      'The Brenner Pass crossing and Italian vignette are included in the fixed price',
      'Direct from arrivals, avoiding a connecting train through Bolzano station',
      'Comfortable for a scenic Dolomites arrival',
    ],
    crossBorder: true,
  },
  {
    slug: 'graz-airport-to-maribor',
    from: 'Graz Airport (GRZ)',
    to: 'Maribor',
    distance: '~100km',
    driveTime: '~1h 15m',
    routeDescription: 'South via the A9 Pyhrn Autobahn and A2 to the Spielfeld border crossing, continuing into Slovenia to Maribor.',
    whyBook: [
      'Direct cross-border arrival transfer for Slovenia\'s wine region',
      'No separate cross-border taxi booking required',
      'Fixed price including the Slovenian vignette',
    ],
    crossBorder: true,
  },
  {
    slug: 'graz-airport-to-klagenfurt',
    from: 'Graz Airport (GRZ)',
    to: 'Klagenfurt',
    distance: '~140km',
    driveTime: '~1h 30m',
    routeDescription: 'West via the A2 Süd Autobahn, a direct cross-region run into the Carinthian lake district.',
    whyBook: [
      'Useful when connecting between Austria\'s two southern airports isn\'t practical by air',
      'Direct to Klagenfurt hotels or the Wörthersee lakefront',
      'Fixed price regardless of traffic',
    ],
  },
  {
    slug: 'linz-airport-to-salzburg',
    from: 'Linz Airport (LNZ)',
    to: 'Salzburg',
    distance: '~130km',
    driveTime: '~1h 25m',
    routeDescription: 'West on the A1 West Autobahn, the same corridor used between the two cities by road.',
    whyBook: [
      'Cross-region business travel without a train transfer through Linz Hauptbahnhof',
      'Direct to Salzburg hotels or the Altstadt',
      'Fixed price agreed before travel',
    ],
  },
  {
    slug: 'linz-airport-to-vienna',
    from: 'Linz Airport (LNZ)',
    to: 'Vienna',
    distance: '~185km',
    driveTime: '~1h 45m – 2h',
    routeDescription: 'East on the A1 West Autobahn along the Danube corridor into Vienna.',
    whyBook: [
      'Business travel connection into the capital without a train changeover',
      'Direct to Vienna hotels or onward to Vienna Airport',
      'Fixed price agreed before travel',
    ],
  },
  {
    slug: 'linz-airport-to-passau',
    from: 'Linz Airport (LNZ)',
    to: 'Passau',
    distance: '~85km',
    driveTime: '~1h',
    routeDescription: 'North via the A7 Mühlkreis Autobahn, crossing into Bavaria near Wegscheid into Passau.',
    whyBook: [
      'Short cross-border transfer for Danube river-cruise passengers embarking or disembarking in Passau',
      'One vehicle for the whole cross-border journey',
      'Fixed price agreed in advance',
    ],
    crossBorder: true,
  },
  {
    slug: 'linz-airport-to-prague',
    from: 'Linz Airport (LNZ)',
    to: 'Prague',
    distance: '~215km',
    driveTime: '~2h 30m',
    routeDescription: 'North via the A7 Mühlkreis Autobahn, crossing into the Czech Republic near Wullowitz onto the D3 towards Prague.',
    whyBook: [
      'Direct capital connection for Linz Airport arrivals',
      'One licensed driver for the whole cross-border journey',
      'Fixed price agreed in advance',
    ],
    crossBorder: true,
  },
  {
    slug: 'klagenfurt-airport-to-ljubljana',
    from: 'Klagenfurt Airport (KLU)',
    to: 'Ljubljana',
    distance: '~85km',
    driveTime: '~1h',
    routeDescription: 'South via the B91 Loiblpass road or the A11 Karawankentunnel directly into Slovenia.',
    whyBook: [
      'Direct capital connection for KLU arrivals, including the tunnel toll',
      'One vehicle for the whole cross-border journey',
      'Fixed price agreed in advance',
    ],
    crossBorder: true,
  },
  {
    slug: 'klagenfurt-airport-to-bad-kleinkirchheim',
    from: 'Klagenfurt Airport (KLU)',
    to: 'Bad Kleinkirchheim',
    distance: '~55km',
    driveTime: '~55m',
    routeDescription: 'West via the A2 and B93 through the Nockberge mountains into Bad Kleinkirchheim.',
    whyBook: [
      'Direct arrival transfer to the spa-and-ski resort, home turf of Franz Klammer',
      'Avoids a regional bus connection from Klagenfurt or Villach',
      'Fixed price with flight tracking included',
    ],
  },
  {
    slug: 'innsbruck-airport-to-alpbach',
    from: 'Innsbruck Airport (INN)',
    to: 'Alpbach',
    distance: '~60km',
    driveTime: '~1h',
    routeDescription: 'East on the A12 Inntal Autobahn, exiting onto the B171/L5 into the Alpbachtal valley.',
    whyBook: [
      'Direct to one of Austria\'s most photographed alpine villages',
      'Also popular for conference and corporate group travel',
      'Fixed price agreed before travel',
    ],
  },
  {
    slug: 'innsbruck-airport-to-obergurgl',
    from: 'Innsbruck Airport (INN)',
    to: 'Obergurgl-Hochgurgl',
    distance: '~90km',
    driveTime: '~1h 30m',
    routeDescription: 'West via the A12 to the Ötztal exit, then south along the B186 Ötztaler Straße to the head of the valley.',
    whyBook: [
      'Direct to Austria\'s highest parish, avoiding a regional bus up the Ötztal',
      'Reliable snow cover well into spring',
      'Fixed transparent price including motorway tolls',
    ],
  },
  {
    slug: 'salzburg-airport-to-flachau',
    from: 'Salzburg Airport (SZG)',
    to: 'Flachau',
    distance: '~80km',
    driveTime: '~45m',
    routeDescription: 'South via the A10 Tauern Autobahn, the closest of the Ski Amadé resort villages to Salzburg Airport.',
    whyBook: [
      'One of the shortest airport-to-resort drives in the Ski Amadé network',
      'Popular for weekend breaks from Salzburg, Vienna, and Munich',
      'Fixed price with flight tracking included',
    ],
  },
  {
    slug: 'graz-airport-to-schladming',
    from: 'Graz Airport (GRZ)',
    to: 'Schladming',
    distance: '~100km',
    driveTime: '~1h 30m',
    routeDescription: 'West via the A9 Pyhrn Autobahn through the Gesäuse into the Ennstal valley and Schladming.',
    whyBook: [
      'Direct route for Styria\'s flagship ski resort from the state\'s own airport',
      'No shuttle bus or regional train changes with ski gear',
      'Fixed rate including motorway tolls',
    ],
  },
  {
    slug: 'klagenfurt-airport-to-nassfeld',
    from: 'Klagenfurt Airport (KLU)',
    to: 'Nassfeld',
    distance: '~65km',
    driveTime: '~1h',
    routeDescription: 'West via the A2 and B111 Gailtal Straße into the Gailtal valley and Nassfeld.',
    whyBook: [
      'Direct to Austria\'s sunniest, most south-facing ski area',
      'Convenient for visitors combining skiing with a trip across the nearby Italian border',
      'Fixed price with flight tracking included',
    ],
  },
  {
    slug: 'klagenfurt-airport-to-turracher-hoehe',
    from: 'Klagenfurt Airport (KLU)',
    to: 'Turracher Höhe',
    distance: '~75km',
    driveTime: '~1h 15m',
    routeDescription: 'Northwest via the B93 and B95 up to the pass-top village of Turracher Höhe.',
    whyBook: [
      'Direct to the twin-lake mountaintop resort straddling Carinthia and Styria',
      'Winter-ready vehicles for the mountain pass approach',
      'Fixed transparent price agreed before travel',
    ],
  },
  {
    slug: 'vienna-to-eisenstadt',
    from: 'Vienna',
    to: 'Eisenstadt',
    distance: '~60km',
    driveTime: '~50m',
    routeDescription: 'South via the A2 and A3 Süd Ost Autobahn into Burgenland\'s wine country and state capital.',
    whyBook: [
      'Direct city-to-city transfer for wine tourism or business travel',
      'No regional bus connection needed',
      'Fixed price door to door',
    ],
  },
  {
    slug: 'graz-to-klagenfurt',
    from: 'Graz',
    to: 'Klagenfurt',
    distance: '~140km',
    driveTime: '~1h 30m',
    routeDescription: 'West via the A2 Süd Autobahn between Austria\'s second and sixth-largest cities.',
    whyBook: [
      'Cross-region business and leisure travel without a regional train transfer',
      'Direct to Klagenfurt hotels or the Wörthersee lakefront',
      'Fixed price regardless of traffic',
    ],
  },
  {
    slug: 'graz-to-schladming',
    from: 'Graz',
    to: 'Schladming',
    distance: '~100km',
    driveTime: '~1h 30m',
    routeDescription: 'West via the A9 Pyhrn Autobahn through the Gesäuse into the Ennstal valley.',
    whyBook: [
      'Popular weekend ski-season route from Styria\'s capital',
      'No station transfer with ski equipment',
      'Fixed rate including motorway tolls',
    ],
  },
  {
    slug: 'salzburg-to-bad-gastein',
    from: 'Salzburg',
    to: 'Bad Gastein',
    distance: '~95km',
    driveTime: '~1h 15m',
    routeDescription:
      'South via the A10 Tauern Autobahn and B167 up the Gastein Valley, the same corridor used from Salzburg Airport.',
    whyBook: [
      'Direct city-to-resort transfer to the historic spa town',
      'Comfortable for winter ski and summer wellness travel alike',
      'Fixed price agreed before travel',
    ],
  },
  {
    slug: 'salzburg-to-st-wolfgang',
    from: 'Salzburg',
    to: 'St. Wolfgang',
    distance: '~50km',
    driveTime: '~50m',
    routeDescription: 'East via the B158 Wolfgangsee Straße through Fuschl into the lakeside village of St. Wolfgang.',
    whyBook: [
      'Popular Salzkammergut day-trip and transfer route',
      'Direct to lakefront hotels, no regional bus timetable',
      'Flexible departure times',
    ],
  },
  {
    slug: 'klagenfurt-to-velden',
    from: 'Klagenfurt',
    to: 'Velden am Wörthersee',
    distance: '~20km',
    driveTime: '~20m',
    routeDescription: 'West via the B83, a short run along the Wörthersee lakefront to Velden.',
    whyBook: [
      'Short, high-frequency transfer for one of Austria\'s best-known lake resorts',
      'Direct to lakefront hotels and casino district',
      'Fixed price door to door',
    ],
  },
  {
    slug: 'villach-to-lienz',
    from: 'Villach',
    to: 'Lienz',
    distance: '~100km',
    driveTime: '~1h 15m',
    routeDescription: 'West via the B100 Drautal Straße, a scenic valley route through East Tyrol into Lienz.',
    whyBook: [
      'Direct cross-region transfer between Carinthia and East Tyrol',
      'Comfortable for the scenic Drau valley drive',
      'Fixed price agreed before travel',
    ],
  },
  {
    slug: 'wels-to-salzburg',
    from: 'Wels',
    to: 'Salzburg',
    distance: '~100km',
    driveTime: '~1h',
    routeDescription: 'West on the A1 West Autobahn, the same corridor used from Linz to Salzburg.',
    whyBook: [
      'Direct business transfer without a train connection through Linz',
      'Fixed price regardless of traffic',
      'Comfortable for trade-fair and conference travel',
    ],
  },
  {
    slug: 'wels-to-linz',
    from: 'Wels',
    to: 'Linz',
    distance: '~30km',
    driveTime: '~25m',
    routeDescription: 'East on the A25 Welser Autobahn, a short direct run between the two Upper Austrian cities.',
    whyBook: [
      'Short, high-frequency business and trade-fair transfer',
      'No regional train changeover needed',
      'Fixed price door to door',
    ],
  },
  {
    slug: 'graz-to-maribor',
    from: 'Graz',
    to: 'Maribor',
    distance: '~100km',
    driveTime: '~1h 15m',
    routeDescription: 'South via the A9 Pyhrn Autobahn and A2 to the Spielfeld border crossing, continuing into Slovenia to Maribor.',
    whyBook: [
      'Short cross-border business run to Slovenia\'s second city',
      'One vehicle for the whole journey, including the border crossing',
      'Fixed price including the Slovenian vignette',
    ],
    crossBorder: true,
  },
  {
    slug: 'linz-to-ceske-budejovice',
    from: 'Linz',
    to: 'České Budějovice',
    distance: '~145km',
    driveTime: '~1h 45m',
    routeDescription: 'North via the A7 Mühlkreis Autobahn, crossing into the Czech Republic near Wullowitz onto the D3.',
    whyBook: [
      'Regional cross-border business connection into South Bohemia',
      'One licensed driver for the whole journey',
      'Fixed price agreed in advance',
    ],
    crossBorder: true,
  },
  {
    slug: 'bregenz-to-st-gallen',
    from: 'Bregenz',
    to: 'St. Gallen',
    distance: '~55km',
    driveTime: '~50m',
    routeDescription: 'West across the Swiss border near Rheineck, a short run into St. Gallen.',
    whyBook: [
      'Short cross-border business run into eastern Switzerland',
      'Swiss vignette included in the fixed price',
      'No separate cross-border taxi booking required',
    ],
    crossBorder: true,
  },
  {
    slug: 'bregenz-to-vaduz',
    from: 'Bregenz',
    to: 'Vaduz',
    distance: '~60km',
    driveTime: '~50m',
    routeDescription: 'South along the Rhine Valley, crossing into Liechtenstein near Feldkirch into Vaduz.',
    whyBook: [
      'Direct cross-border transfer for Liechtenstein\'s finance sector',
      'One vehicle for the whole journey, including two border crossings',
      'Fixed price agreed in advance',
    ],
    crossBorder: true,
  },
  {
    slug: 'eisenstadt-to-sopron',
    from: 'Eisenstadt',
    to: 'Sopron',
    distance: '~25km',
    driveTime: '~25m',
    routeDescription: 'A short cross-border hop via the B84, crossing into Hungary near Klingenbach into Sopron.',
    whyBook: [
      'Very short cross-border run between two wine-region capitals',
      'No separate cross-border taxi booking required',
      'Fixed price with the border crossing included',
    ],
    crossBorder: true,
  },
  {
    slug: 'wiener-neustadt-to-sopron',
    from: 'Wiener Neustadt',
    to: 'Sopron',
    distance: '~45km',
    driveTime: '~40m',
    routeDescription: 'Southeast via the S4 and B61, crossing into Hungary near Deutschkreutz into Sopron.',
    whyBook: [
      'Short cross-border business or spa-tourism run',
      'One vehicle for the whole journey, including the border crossing',
      'Fixed price agreed in advance',
    ],
    crossBorder: true,
  },
  {
    slug: 'feldkirch-to-vaduz',
    from: 'Feldkirch',
    to: 'Vaduz',
    distance: '~20km',
    driveTime: '~20m',
    routeDescription: 'A very short cross-border run along the Rhine Valley into Liechtenstein\'s capital.',
    whyBook: [
      'The shortest cross-border route on the network',
      'Popular for Liechtenstein business and banking travel',
      'Fixed price with the border crossing included',
    ],
    crossBorder: true,
  },
  {
    slug: 'dornbirn-to-zurich',
    from: 'Dornbirn',
    to: 'Zurich',
    distance: '~110km',
    driveTime: '~1h 15m',
    routeDescription: 'West via the Swiss border near St. Margrethen onto the Swiss A1 motorway to Zurich.',
    whyBook: [
      'Cross-border business route for Vorarlberg\'s largest city',
      'Swiss vignette included in the fixed price',
      'One vehicle for the whole journey',
    ],
    crossBorder: true,
  },
  {
    slug: 'kufstein-to-munich',
    from: 'Kufstein',
    to: 'Munich',
    distance: '~100km',
    driveTime: '~1h 15m',
    routeDescription: 'North via the German A93/A8 corridor, a short cross-border run from the Tyrolean border town to Munich.',
    whyBook: [
      'Short cross-border business or leisure route into Bavaria',
      'One vehicle for the whole journey, including the German border crossing',
      'Fixed price agreed in advance',
    ],
    crossBorder: true,
  },
  {
    slug: 'villach-to-bad-kleinkirchheim',
    from: 'Villach',
    to: 'Bad Kleinkirchheim',
    distance: '~35km',
    driveTime: '~40m',
    routeDescription: 'North via the B93 through the Nockberge mountains into Bad Kleinkirchheim.',
    whyBook: [
      'Short resort transfer for the spa-and-ski town, home turf of Franz Klammer',
      'Direct to ski-in/ski-out hotels',
      'Fixed price door to door',
    ],
  },
  {
    slug: 'zell-am-see-to-bad-gastein',
    from: 'Zell am See',
    to: 'Bad Gastein',
    distance: '~35km',
    driveTime: '~40m',
    routeDescription: 'South via the B311 and B167 through the Gasteinertal valley to Bad Gastein.',
    whyBook: [
      'Short resort-to-resort transfer for guests splitting a trip between two Salzburg-state valleys',
      'No regional bus connection needed',
      'Fixed price door to door',
    ],
  },
]
