export type RoutePair = {
  slug: string
  from: string
  to: string
  distance: string
  driveTime: string
  routeDescription: string
  whyBook: string[]
  crossBorder?: boolean
  // Overrides the generated <title>/description in generateMetadata — only
  // set this where the templated copy genuinely underperforms (see the GSC
  // signal audit); leave unset everywhere else so the template stays DRY.
  seoTitle?: string
  seoDescription?: string
}

export const routes: RoutePair[] = [
  {
    slug: 'vienna-airport-to-salzburg',
    from: 'Vienna Airport (VIE)',
    to: 'Salzburg',
    distance: '~300km',
    driveTime: '~2h 45m – 3h',
    routeDescription:
      'The route runs west on the A1 West Autobahn, Austria\'s main east-west corridor, passing Linz before continuing to Salzburg.',
    whyBook: [
      'Avoids a connecting train or a second flight for a same-day arrival',
      'One flat rate regardless of traffic or a delayed landing',
      'Direct to your Salzburg hotel or the Altstadt, no station transfer',
    ],
  },
  {
    slug: 'vienna-airport-to-graz',
    from: 'Vienna Airport (VIE)',
    to: 'Graz',
    distance: '~200km',
    driveTime: '~2h 15m',
    routeDescription:
      'The route follows the A2 Süd Autobahn south through Lower Austria and Styria directly into Graz.',
    whyBook: [
      'One of the more direct airport-to-city runs in Austria',
      'Useful when Graz Airport (GRZ) doesn\'t have a convenient connection from your origin',
      'Fixed price with flight tracking included',
    ],
  },
  {
    slug: 'vienna-to-salzburg',
    from: 'Vienna',
    to: 'Salzburg',
    distance: '~295km',
    driveTime: '~2h 45m',
    routeDescription:
      'A straight run west on the A1 West Autobahn, the same corridor used for the airport route but starting from central Vienna.',
    whyBook: [
      'Faster door-to-door than the train once you factor in getting to and from stations',
      'Room for luggage that doesn\'t suit a train compartment',
      'Depart at the time that works for you, not a fixed timetable',
    ],
  },
  {
    slug: 'vienna-to-graz',
    from: 'Vienna',
    to: 'Graz',
    distance: '~195km',
    driveTime: '~2h',
    routeDescription: 'South on the A2 Süd Autobahn, one of the more scenic Autobahn routes in Austria as it climbs through Lower Austria into Styria.',
    whyBook: [
      'Direct city-center to city-center in about two hours',
      'A common route for business trips between Austria\'s two largest cities',
      'No need to switch to regional transport at either end',
    ],
  },
  {
    slug: 'salzburg-to-innsbruck',
    from: 'Salzburg',
    to: 'Innsbruck',
    distance: '~140–200km',
    driveTime: '~1h 30m – 2h 15m',
    routeDescription:
      'The fastest route briefly crosses into Bavaria on the German A8 Autobahn before re-entering Austria near Kufstein onto the A12 — a shortcut many drivers use. A fully domestic alternative runs via the B178/A12 through Kitzbühel and Wörgl, slightly longer but avoiding the border crossing.',
    whyBook: [
      'We handle the German-Austrian border crossing as part of the fixed price — no separate booking needed',
      'One vehicle the whole way, whichever route is faster on the day',
      'Popular for connecting two of Austria\'s most-visited cities without a flight',
    ],
    crossBorder: true,
  },
  {
    slug: 'linz-to-vienna',
    from: 'Linz',
    to: 'Vienna',
    distance: '~185km',
    driveTime: '~1h 45m – 2h',
    routeDescription: 'East on the A1 West Autobahn, the same corridor used for Vienna–Salzburg traffic, running along the Danube valley for part of the way.',
    whyBook: [
      'A common route for business travel between Upper Austria and the capital',
      'Direct to Vienna Airport as an add-on if you\'re connecting to a flight',
      'Fixed price agreed before you travel',
    ],
  },
  {
    slug: 'vienna-to-bratislava',
    from: 'Vienna',
    to: 'Bratislava',
    distance: '~80km',
    driveTime: '~1h',
    routeDescription:
      'One of the shortest cross-border capital-to-capital drives in Europe, via the A6 motorway through Kittsee to the Slovak border.',
    whyBook: [
      'Fast enough for a same-day round trip',
      'No vehicle switch or paperwork at the border — it\'s handled as part of the service',
      'Popular for business meetings, day trips, and Vienna Airport connections',
    ],
    crossBorder: true,
    seoTitle: 'Vienna to Bratislava Private Transfer | 1 Hour, Fixed Price',
    seoDescription:
      'Private chauffeur transfer from central Vienna to Bratislava — 80km, about an hour, fixed price, no border stop. Ideal for meetings, day trips, and hotel-to-hotel travel.',
  },
  {
    slug: 'vienna-to-budapest',
    from: 'Vienna',
    to: 'Budapest',
    distance: '~245km',
    driveTime: '~2h 30m – 3h',
    routeDescription:
      'Southeast via the A4 Autobahn to the Hungarian border at Hegyeshalom, continuing on the M15/M1 into Budapest.',
    whyBook: [
      'Direct alternative to a connecting flight or train transfer',
      'One licensed driver the whole way, including the border crossing',
      'Comfortable for business trips or weekend travel between the two capitals',
    ],
    crossBorder: true,
  },
  {
    slug: 'salzburg-to-munich',
    from: 'Salzburg',
    to: 'Munich',
    distance: '~145km',
    driveTime: '~1h 30m',
    routeDescription: 'A short cross-border run north on the German A8 Autobahn — one of the most frequently booked international routes from Salzburg.',
    whyBook: [
      'Popular for connecting to Munich Airport (MUC) for onward international flights',
      'No need to book a separate cross-border taxi or transfer service',
      'Fixed price agreed in advance, regardless of border traffic',
    ],
    crossBorder: true,
  },
  {
    slug: 'innsbruck-airport-to-kitzbuehel',
    from: 'Innsbruck Airport (INN)',
    to: 'Kitzbühel',
    distance: '~90km',
    driveTime: '~1h',
    routeDescription: 'East on the A12 Inntal Autobahn before turning onto the B170/B161 into Kitzbühel — the most direct airport-to-resort route in the region.',
    whyBook: [
      'Winter-ready vehicles with space for skis and boards',
      'Direct to your chalet or hotel, no shuttle bus transfer',
      'The shortest airport-to-resort drive time of any major Tyrolean ski town',
    ],
  },
  {
    slug: 'innsbruck-airport-to-st-anton',
    from: 'Innsbruck Airport (INN)',
    to: 'St. Anton am Arlberg',
    distance: '~100km',
    driveTime: '~1h 10m',
    routeDescription: 'West on the A12 Inntal Autobahn and S16 Arlberg Schnellstraße directly into St. Anton.',
    whyBook: [
      'Direct 4x4 luxury transfer to your Arlberg chalet',
      'Spacious vans for ski equipment and large bags',
      'Flight tracking and driver meet & greet inside INN arrival hall',
    ],
  },
  {
    slug: 'innsbruck-airport-to-ischgl',
    from: 'Innsbruck Airport (INN)',
    to: 'Ischgl',
    distance: '~100km',
    driveTime: '~1h 15m',
    routeDescription: 'West via A12 Inntal Autobahn and B188 Silvretta Straße up the Paznaun Valley to Ischgl.',
    whyBook: [
      'Smooth Paznaun Valley transfer with experienced Alpine drivers',
      'Fixed transparent pricing with zero mountain toll surcharges',
      'Luxury Mercedes fleet equipped for winter snow conditions',
    ],
  },
  {
    slug: 'innsbruck-airport-to-soelden',
    from: 'Innsbruck Airport (INN)',
    to: 'Sölden',
    distance: '~85km',
    driveTime: '~1h 10m',
    routeDescription: 'West via A12 to Ötztal exit, then south along the B186 Ötztaler Straße into Sölden.',
    whyBook: [
      'Fastest private transfer from INN to the Ötztal glacier area',
      'Direct delivery to Sölden hotels and 007 Elements base',
      'All-inclusive fixed rate with flight delay monitoring',
    ],
  },
  {
    slug: 'innsbruck-airport-to-mayrhofen',
    from: 'Innsbruck Airport (INN)',
    to: 'Mayrhofen',
    distance: '~75km',
    driveTime: '~1h',
    routeDescription: 'East via A12 Inntal Autobahn, exit Zillertal onto B169 directly to Mayrhofen.',
    whyBook: [
      'Direct Zillertal valley transfer with zero train changes',
      'Winter-equipped vehicles for Hintertux glacier visitors',
      'Personalized pickup right outside Innsbruck arrivals',
    ],
  },
  {
    slug: 'innsbruck-airport-to-lech',
    from: 'Innsbruck Airport (INN)',
    to: 'Lech am Arlberg',
    distance: '~120km',
    driveTime: '~1h 30m',
    routeDescription: 'West via A12 and S16 through the Arlberg Pass or Flexenpass tunnel into Lech.',
    whyBook: [
      'Exclusive VIP transfer service to luxury 5-star Arlberg hotels',
      'Professional chauffeurs trained for heavy winter pass driving',
      'Spacious V-Class and S-Class vehicles available',
    ],
  },
  {
    slug: 'salzburg-airport-to-kitzbuehel',
    from: 'Salzburg Airport (SZG)',
    to: 'Kitzbühel',
    distance: '~75km',
    driveTime: '~1h 15m',
    routeDescription: 'Southwest via Loferer Straße (B178) through Unken and Waidring into Kitzbühel.',
    whyBook: [
      'Popular ski route for charter flights landing at SZG',
      'Comfortable door-to-door service directly to Kitzbühel chalets',
      'No hassle carrying heavy ski bags on regional public transport',
    ],
  },
  {
    slug: 'salzburg-airport-to-zell-am-see',
    from: 'Salzburg Airport (SZG)',
    to: 'Zell am See',
    distance: '~80km',
    driveTime: '~1h 15m',
    routeDescription: 'South via A10 Tauern Autobahn or B311 Pinzgauer Straße to Zell am See.',
    whyBook: [
      'Direct lakefront and Kaprun glacier resort transfer',
      'Fixed rate inclusive of luggage, ski gear, and tolls',
      'Available 24/7 for early morning ski charter arrivals',
    ],
  },
  {
    slug: 'salzburg-airport-to-saalbach',
    from: 'Salzburg Airport (SZG)',
    to: 'Saalbach-Hinterglemm',
    distance: '~85km',
    driveTime: '~1h 20m',
    routeDescription: 'Southwest via B178 and B311 into the Glemmtal valley towards Saalbach.',
    whyBook: [
      'Hassle-free access to the Skicircus ski resort area',
      'Spacious minibuses and Mercedes V-Class for groups & families',
      'Direct drop-off at your hotel door',
    ],
  },
  {
    slug: 'salzburg-airport-to-bad-gastein',
    from: 'Salzburg Airport (SZG)',
    to: 'Bad Gastein',
    distance: '~95km',
    driveTime: '~1h 15m',
    routeDescription: 'South via A10 Tauern Autobahn and B167 up the Gastein Valley to Bad Gastein.',
    whyBook: [
      'Scenic valley drive straight to historic Belle Époque spa hotels',
      'Comfortable ride for winter ski and summer wellness guests',
      'Fixed transparent price with flight delay tracking included',
    ],
  },
  {
    slug: 'munich-airport-to-innsbruck',
    from: 'Munich Airport (MUC)',
    to: 'Innsbruck',
    distance: '~160km',
    driveTime: '~2h',
    routeDescription: 'South via German A9 and A8 Autobahns, crossing into Austria via A93/A12 Inntal Autobahn to Innsbruck.',
    whyBook: [
      'Seamless cross-border transfer from Germany’s top long-haul hub',
      'No train changes with heavy luggage at Munich Central Station',
      'Licensed cross-border chauffeurs with fixed pricing',
    ],
    crossBorder: true,
  },
  {
    slug: 'munich-airport-to-salzburg',
    from: 'Munich Airport (MUC)',
    to: 'Salzburg',
    distance: '~170km',
    driveTime: '~1h 45m',
    routeDescription: 'East via German A92 and A8 Autobahn, crossing the Austrian border at Walserberg directly to Salzburg.',
    whyBook: [
      'Direct link between MUC long-haul flights and Salzburg Altstadt',
      'Avoids German railway delays or rental car drop-off fees',
      'Professional meet & greet service in MUC Terminal 1 or 2',
    ],
    crossBorder: true,
  },
  {
    slug: 'munich-airport-to-kitzbuehel',
    from: 'Munich Airport (MUC)',
    to: 'Kitzbühel',
    distance: '~165km',
    driveTime: '~2h',
    routeDescription: 'South via A8 towards Inntal Dreieck, continuing via A93/B173 through Kufstein to Kitzbühel.',
    whyBook: [
      'Top choice for international long-haul travelers heading to Kitzbühel',
      '4x4 vehicles equipped for winter snow conditions across Bavaria/Tyrol',
      'One vehicle and driver door-to-door without border delays',
    ],
    crossBorder: true,
  },
  {
    slug: 'munich-airport-to-st-anton',
    from: 'Munich Airport (MUC)',
    to: 'St. Anton am Arlberg',
    distance: '~240km',
    driveTime: '~2h 45m',
    routeDescription: 'South via A95 or A8/A12 through the Inntal valley to Arlberg.',
    whyBook: [
      'Direct executive transfer for overseas visitors arriving in Munich',
      'Spacious V-Class and SUV fleet for ski luggage',
      'All border toll vignettes and fees included in fixed fare',
    ],
    crossBorder: true,
  },
  {
    slug: 'zurich-airport-to-lech',
    from: 'Zurich Airport (ZRH)',
    to: 'Lech am Arlberg',
    distance: '~195km',
    driveTime: '~2h 15m',
    routeDescription: 'East via Swiss A1/A3 motorways, past Lake Walen, entering Austria near Feldkirch to Lech.',
    whyBook: [
      'The premier luxury transfer route from Zurich to Arlberg 5-star resorts',
      'Licensed for Swiss-Austrian international chauffeur transfers',
      'Discreet executive service for high-net-worth travelers',
    ],
    crossBorder: true,
  },
  {
    slug: 'zurich-airport-to-st-anton',
    from: 'Zurich Airport (ZRH)',
    to: 'St. Anton am Arlberg',
    distance: '~200km',
    driveTime: '~2h 15m',
    routeDescription: 'East across Switzerland via A3/A13, entering Vorarlberg/Tyrol via Arlberg Pass or tunnel.',
    whyBook: [
      'Preferred route for international arrivals via Zurich Kloten',
      'Spacious luxury Mercedes vans for families and ski equipment',
      'Fixed cross-border pricing with zero surprise charges',
    ],
    crossBorder: true,
  },
  {
    slug: 'vienna-airport-to-bratislava',
    from: 'Vienna Airport (VIE)',
    to: 'Bratislava',
    distance: '~65km',
    driveTime: '~45m',
    routeDescription: 'East via A4 and A6 motorways through Kittsee across the border to Bratislava — booked in either direction, arrival or departure.',
    whyBook: [
      'Shortest capital-to-capital transfer in Central Europe',
      'Covers both directions — VIE arrivals heading into Slovakia, and Bratislava departures connecting to a flight at Vienna Airport',
      'Fast, direct, and fixed price door-to-door',
    ],
    crossBorder: true,
    seoTitle: 'Vienna Airport to Bratislava Transfer | 45 Minutes, Fixed Price',
    seoDescription:
      'Private transfer between Vienna Airport and Bratislava — 65km, ~45 minutes, fixed price door-to-door. Covers both arrivals into VIE and departures from Bratislava.',
  },
  {
    slug: 'vienna-airport-to-budapest',
    from: 'Vienna Airport (VIE)',
    to: 'Budapest',
    distance: '~230km',
    driveTime: '~2h 15m',
    routeDescription: 'Southeast via A4 Autobahn and Hungarian M1 motorway directly to Budapest.',
    whyBook: [
      'High-demand long-distance airport-to-capital transfer',
      'Avoids airport transit connections or train station transfers',
      'Professional bilingual driver comfortable with international routes',
    ],
    crossBorder: true,
  },
  {
    slug: 'vienna-airport-to-hallstatt',
    from: 'Vienna Airport (VIE)',
    to: 'Hallstatt',
    distance: '~300km',
    driveTime: '~3h 15m',
    routeDescription: 'West via A1 West Autobahn to Regau exit, continuing through Gmunden & Bad Ischl to Hallstatt.',
    whyBook: [
      'Direct luxury tour/transfer from Vienna Airport to UNESCO Hallstatt',
      'No complicated multi-leg train and ferry connections with luggage',
      'Option to add scenic stops in the Salzkammergut region',
    ],
  },
  {
    slug: 'salzburg-to-hallstatt',
    from: 'Salzburg',
    to: 'Hallstatt',
    distance: '~75km',
    driveTime: '~1h 15m',
    routeDescription: 'East via B158 Wolfgangsee Straße through Fuschl and St. Gilgen, then B145 to Hallstatt.',
    whyBook: [
      'Most popular day trip and private transfer route from Salzburg',
      'Stunning scenic drive through Lake Fuschl and Wolfgangsee',
      'Flexible departure times tailored to your itinerary',
    ],
  },
  {
    slug: 'salzburg-airport-to-schladming',
    from: 'Salzburg Airport (SZG)',
    to: 'Schladming',
    distance: '~90km',
    driveTime: '~1h',
    routeDescription: 'South via A10 Tauern Autobahn and B320 Ennstal Straße directly to Schladming.',
    whyBook: [
      'Fastest gateway access to Planai and Ski Amadé 4-Mountain area',
      'Fixed rate including Tauern motorway toll fees',
      'Direct hotel drop-off without carrying ski gear on public trains',
    ],
  },
  {
    slug: 'salzburg-airport-to-obertauern',
    from: 'Salzburg Airport (SZG)',
    to: 'Obertauern',
    distance: '~90km',
    driveTime: '~1h 10m',
    routeDescription: 'South via A10 Tauern Autobahn to Radstadt exit, up B99 Radstädter Tauern Straße to Obertauern.',
    whyBook: [
      'Direct transfer to snow-sure high altitude pass resort',
      '4x4 luxury vehicles experienced in heavy winter mountain driving',
      'All-inclusive fixed price with flight delay monitoring',
    ],
  },
  {
    slug: 'munich-airport-to-saalbach',
    from: 'Munich Airport (MUC)',
    to: 'Saalbach-Hinterglemm',
    distance: '~215km',
    driveTime: '~2h 30m',
    routeDescription: 'South via German A8, crossing into Austria via Siegsdorf/Lofer (B178) into Glemmtal.',
    whyBook: [
      'Popular international long-haul transfer for UK and Scandinavian skiers',
      'Large Mercedes V-Class vans for groups with heavy ski baggage',
      'No border hassle or highway vignette worries',
    ],
    crossBorder: true,
  },
  {
    slug: 'munich-airport-to-zell-am-see',
    from: 'Munich Airport (MUC)',
    to: 'Zell am See',
    distance: '~200km',
    driveTime: '~2h 15m',
    routeDescription: 'South via A8 motorway and B311 Pinzgauer Straße directly to Lake Zell.',
    whyBook: [
      'Direct transfers for long-haul MUC arrivals heading to Zell & Kaprun glacier',
      'Fixed transparent price agreed in advance',
      'Full flight tracking and arrivals hall meet-and-greet',
    ],
    crossBorder: true,
  },
  {
    slug: 'munich-airport-to-mayrhofen',
    from: 'Munich Airport (MUC)',
    to: 'Mayrhofen',
    distance: '~190km',
    driveTime: '~2h 15m',
    routeDescription: 'South via A8 and A93/A12 Inntal corridor, exit Zillertal (B169) into Mayrhofen.',
    whyBook: [
      'Direct luxury chauffeur transfer from MUC straight to Zillertal valley',
      'Spacious vans accommodating glacier ski gear',
      'Comfortable door-to-door journey avoiding crowded Munich trains',
    ],
    crossBorder: true,
  },
  {
    slug: 'munich-airport-to-soelden',
    from: 'Munich Airport (MUC)',
    to: 'Sölden',
    distance: '~240km',
    driveTime: '~2h 45m',
    routeDescription: 'South via German Autobahn network and A12/B186 into the Ötztal valley.',
    whyBook: [
      'Reliable cross-border transfer for long-haul international visitors',
      'All toll fees and vignettes included in fixed quote',
      '4x4 Mercedes vehicles tailored for Alpine snow roads',
    ],
    crossBorder: true,
  },
  {
    slug: 'zurich-airport-to-ischgl',
    from: 'Zurich Airport (ZRH)',
    to: 'Ischgl',
    distance: '~235km',
    driveTime: '~2h 30m',
    routeDescription: 'East across Swiss motorways A3/A13, entering Austria at Feldkirch onto S16/B188 Paznaun.',
    whyBook: [
      'High-end VIP cross-border transfer service for Zurich arrivals',
      'Experienced Swiss-Austrian cross-border chauffeurs',
      'Discreet and comfortable executive travel',
    ],
    crossBorder: true,
  },
  {
    slug: 'graz-to-ljubljana',
    from: 'Graz',
    to: 'Ljubljana',
    distance: '~195km',
    driveTime: '~2h',
    routeDescription: 'South via the A2 Süd Autobahn through the Spielfeld border crossing into Slovenia onto the A1 motorway.',
    whyBook: [
      'Seamless regional cross-border connection between Styria and Slovenia',
      'Ideal for business trips and diplomatic travel',
      'Fixed rate with Slovenian highway vignette included',
    ],
    crossBorder: true,
  },
  {
    slug: 'graz-to-venice',
    from: 'Graz',
    to: 'Venice',
    distance: '~380km',
    driveTime: '~3h 45m',
    routeDescription: 'Southwest via A2 Süd Autobahn, crossing Tarvisio border into Italy on A23/A4 to Venice.',
    whyBook: [
      'Exclusive private intercity transfer to the Venetian lagoon (Piazzale Roma)',
      'Comfortable long-distance Mercedes sedan or van ride',
      'Flexible stops along the route in Carinthia or Friuli',
    ],
    crossBorder: true,
  },
  {
    slug: 'klagenfurt-to-ljubljana',
    from: 'Klagenfurt',
    to: 'Ljubljana',
    distance: '~85km',
    driveTime: '~1h',
    routeDescription: 'South via B91 Loiblpass or A11 Karawankentunnel directly into Slovenia.',
    whyBook: [
      'Fastest cross-border transfer between Carinthia and Ljubljana',
      'Karawankentunnel toll fees included in fixed quote',
      'Door-to-door hotel and business transfer',
    ],
    crossBorder: true,
  },
  {
    slug: 'klagenfurt-to-venice',
    from: 'Klagenfurt',
    to: 'Venice',
    distance: '~280km',
    driveTime: '~2h 45m',
    routeDescription: 'Southwest via A2 Süd Autobahn across the Italian border via Udine (A23) to Venice.',
    whyBook: [
      'Direct Alpine-to-Adriatic luxury chauffeur transfer',
      'No train transfers carrying heavy cruise or holiday luggage',
      'Licensed for international Italian pickups and drop-offs',
    ],
    crossBorder: true,
  },
  {
    slug: 'vienna-to-prague',
    from: 'Vienna',
    to: 'Prague',
    distance: '~310km',
    driveTime: '~3h 15m',
    routeDescription: 'North via A5 Weinviertel Autobahn into Czech Republic via Mikulov on D52/D1 to Prague.',
    whyBook: [
      'Top-tier capital-to-capital private transfer in Central Europe',
      'Direct pick-up from Vienna hotels to Prague Castle or Old Town',
      'All Czech highway vignette fees included',
    ],
    crossBorder: true,
  },
  {
    slug: 'salzburg-to-graz',
    from: 'Salzburg',
    to: 'Graz',
    distance: '~280km',
    driveTime: '~2h 45m',
    routeDescription: 'Southeast via A10 Tauern Autobahn and A9 Pyhrn Autobahn through Ennstal valley.',
    whyBook: [
      'Connects Austria’s premier festival city with Styria’s capital',
      'Comfortable intercity transfer avoiding regional train connections',
      'Fixed pricing with mountain tunnel tolls included',
    ],
  },
  {
    slug: 'bregenz-to-zurich-airport',
    from: 'Bregenz',
    to: 'Zurich Airport (ZRH)',
    distance: '~120km',
    driveTime: '~1h 15m',
    routeDescription: 'West across the Swiss border (Höchst/St. Margrethen) via Swiss A1 motorway to Zurich Kloten.',
    whyBook: [
      'Primary airport connection for Vorarlberg residents and businesses',
      'Cross-border licensed driver with Swiss vignette included',
      'Punctual airport transfers with flight tracking',
    ],
    crossBorder: true,
  },
  {
    slug: 'innsbruck-to-zurich',
    from: 'Innsbruck',
    to: 'Zurich',
    distance: '~290km',
    driveTime: '~3h',
    routeDescription: 'West via A12/S16 through Arlberg, crossing Liechtenstein/Switzerland border on A3 to Zurich.',
    whyBook: [
      'Direct city-to-city transfer connecting Tyrol with Zurich financial district',
      'Comfortable executive ride with optional stops in Vaduz or Bregenz',
      'Fixed rate covering all international transit fees',
    ],
    crossBorder: true,
  },
  {
    slug: 'vienna-to-wachau',
    from: 'Vienna',
    to: 'Wachau Valley',
    distance: '~85km',
    driveTime: '~1h',
    routeDescription: 'West along A1 and S33 to Krems and the scenic Danube wine valley (Dürnstein/Melk).',
    whyBook: [
      'Private day-tour and wine tasting transfer with a dedicated driver',
      'Flexible itinerary with stops at Melk Abbey and vineyards',
      'Fixed daily or transfer pricing',
    ],
  },
  {
    slug: 'vienna-to-baden-wien',
    from: 'Vienna',
    to: 'Baden bei Wien',
    distance: '~30km',
    driveTime: '~35m',
    routeDescription: 'South via A2 Süd Autobahn directly into the spa town of Baden.',
    whyBook: [
      'Quick executive transfer to Baden Thermal Spa and Casino',
      'Ideal for hotel guests, evening casino visits, and wellness retreats',
      'Fixed price door-to-door',
    ],
  },
  {
    slug: 'bregenz-to-lech',
    from: 'Bregenz',
    to: 'Lech am Arlberg',
    distance: '~95km',
    driveTime: '~1h 15m',
    routeDescription: 'Southeast via Rheintal Autobahn A14 and B197 up the Flexenpass to Lech.',
    whyBook: [
      'Direct Vorarlberg valley connection to luxury Arlberg resort',
      'Experienced mountain chauffeurs for heavy winter snowfall',
      'Spacious V-Class luxury vans for families and ski gear',
    ],
  },
  {
    slug: 'bregenz-to-st-anton',
    from: 'Bregenz',
    to: 'St. Anton am Arlberg',
    distance: '~105km',
    driveTime: '~1h 20m',
    routeDescription: 'Southeast via A14 and S16 Arlberg Schnellstraße to St. Anton.',
    whyBook: [
      'Fast, direct transfer connecting Lake Constance with the Arlberg ski area',
      'All mountain tunnel tolls included',
      'Fixed rate with professional chauffeur',
    ],
  },
  {
    slug: 'linz-to-salzburg',
    from: 'Linz',
    to: 'Salzburg',
    distance: '~130km',
    driveTime: '~1h 25m',
    routeDescription: 'West via A1 West Autobahn connecting Upper Austria with Salzburg state.',
    whyBook: [
      'Frequent intercity transfer for business and leisure travelers',
      'Avoids train station transfers with heavy luggage',
      'Direct hotel or Linz/Salzburg airport connection',
    ],
  },
  {
    slug: 'villach-to-venice',
    from: 'Villach',
    to: 'Venice',
    distance: '~240km',
    driveTime: '~2h 30m',
    routeDescription: 'Southwest via A2 Süd Autobahn across Tarvisio Italian border via Udine (A23/A4) to Venice.',
    whyBook: [
      'Shortest luxury cross-border drive from Carinthia to the Venetian coast',
      'Direct drop-off at Piazzale Roma or Venice cruise port terminal',
      'Licensed for international Italian pickups and drop-offs',
    ],
    crossBorder: true,
  },
  {
    slug: 'villach-to-ljubljana',
    from: 'Villach',
    to: 'Ljubljana',
    distance: '~100km',
    driveTime: '~1h',
    routeDescription: 'South via A11 Karawankentunnel directly into Slovenia to Ljubljana.',
    whyBook: [
      'Fastest cross-border connection between Carinthia and Ljubljana Airport/City',
      'Tunnel tolls and Slovenian highway vignette included',
      '24/7 private transfer availability',
    ],
    crossBorder: true,
  },
]
