export type RoutePair = {
  slug: string
  from: string
  to: string
  distance: string
  driveTime: string
  routeDescription: string
  whyBook: string[]
  crossBorder?: boolean
  seoTitle?: string
  seoDescription?: string
}

export const routes: RoutePair[] = [
  {
    slug: 'vienna-airport-to-salzburg',
    from: 'Flughafen Wien (VIE)',
    to: 'Salzburg',
    distance: '~300 km',
    driveTime: '~2 Std. 45 Min. – 3 Std.',
    routeDescription:
      'Die Route führt auf der A1 Westautobahn, Österreichs wichtigster Ost-West-Achse, an Linz vorbei weiter nach Salzburg.',
    whyBook: [
      'Kein Umsteigen auf Zug oder Anschlussflug für eine Ankunft am selben Tag',
      'Ein Festpreis unabhängig von Verkehr oder verspäteter Landung',
      'Direkt zu Ihrem Hotel in Salzburg oder in die Altstadt, kein Bahnhofstransfer',
    ],
  },
  {
    slug: 'vienna-airport-to-graz',
    from: 'Flughafen Wien (VIE)',
    to: 'Graz',
    distance: '~200 km',
    driveTime: '~2 Std. 15 Min.',
    routeDescription:
      'Die Route folgt der A2 Südautobahn durch Niederösterreich und die Steiermark direkt nach Graz.',
    whyBook: [
      'Eine der direkteren Flughafen-zu-Stadt-Strecken in Österreich',
      'Nützlich, wenn der Flughafen Graz (GRZ) keine passende Verbindung von Ihrem Startort bietet',
      'Festpreis inklusive Flugverfolgung',
    ],
  },
  {
    slug: 'vienna-to-salzburg',
    from: 'Wien',
    to: 'Salzburg',
    distance: '~295 km',
    driveTime: '~2 Std. 45 Min.',
    routeDescription:
      'Eine direkte Fahrt auf der A1 Westautobahn — dieselbe Route wie zum Flughafen, jedoch ab dem Wiener Stadtzentrum.',
    whyBook: [
      'Schneller von Tür zu Tür als der Zug, sobald man Anfahrt und Abholung an den Bahnhöfen mitrechnet',
      'Platz für Gepäck, das nicht ins Zugabteil passt',
      'Abfahrt zur passenden Zeit, kein fester Fahrplan',
    ],
  },
  {
    slug: 'vienna-to-graz',
    from: 'Wien',
    to: 'Graz',
    distance: '~195 km',
    driveTime: '~2 Std.',
    routeDescription: 'Südwärts auf der A2 Südautobahn, eine der landschaftlich schönsten Autobahnstrecken Österreichs, die durch Niederösterreich in die Steiermark führt.',
    whyBook: [
      'Direkt vom Stadtzentrum zum Stadtzentrum in rund zwei Stunden',
      'Eine übliche Strecke für Geschäftsreisen zwischen Österreichs zwei größten Städten',
      'Kein Umstieg auf Regionalverkehr an beiden Enden nötig',
    ],
  },
  {
    slug: 'salzburg-to-innsbruck',
    from: 'Salzburg',
    to: 'Innsbruck',
    distance: '~140–200 km',
    driveTime: '~1 Std. 30 Min. – 2 Std. 15 Min.',
    routeDescription:
      'Die schnellste Route führt kurz über die deutsche A8 durch Bayern, bevor sie bei Kufstein wieder auf die österreichische A12 wechselt. Eine rein österreichische Alternative verläuft über die B178/A12 durch Kitzbühel und Wörgl, etwas länger, aber ohne Grenzübertritt.',
    whyBook: [
      'Wir übernehmen den deutsch-österreichischen Grenzübertritt als Teil des Festpreises — keine separate Buchung nötig',
      'Ein Fahrzeug die ganze Strecke, je nachdem welche Route an dem Tag schneller ist',
      'Beliebt, um zwei der meistbesuchten Städte Österreichs ohne Flug zu verbinden',
    ],
    crossBorder: true,
  },
  {
    slug: 'linz-to-vienna',
    from: 'Linz',
    to: 'Wien',
    distance: '~185 km',
    driveTime: '~1 Std. 45 Min. – 2 Std.',
    routeDescription: 'Ostwärts auf der A1 Westautobahn, derselben Achse wie zwischen Wien und Salzburg, streckenweise entlang des Donautals.',
    whyBook: [
      'Eine übliche Strecke für Geschäftsreisen zwischen Oberösterreich und der Hauptstadt',
      'Direkt zum Flughafen Wien als Zusatzstopp bei einem Weiterflug',
      'Festpreis vor Fahrtantritt vereinbart',
    ],
  },
  {
    slug: 'vienna-to-bratislava',
    from: 'Wien',
    to: 'Bratislava',
    distance: '~80 km',
    driveTime: '~1 Std.',
    routeDescription:
      'Eine der kürzesten grenzüberschreitenden Hauptstadt-zu-Hauptstadt-Fahrten Europas, über die A6-Autobahn durch Kittsee bis zur slowakischen Grenze.',
    whyBook: [
      'Schnell genug für eine Rückfahrt am selben Tag',
      'Kein Fahrzeugwechsel oder Papierkram an der Grenze — das übernehmen wir',
      'Beliebt für Geschäftstermine, Tagesausflüge und Anschlüsse an den Flughafen Wien',
    ],
    crossBorder: true,
    seoTitle: 'Wien nach Bratislava Privattransfer | 1 Stunde, Festpreis',
    seoDescription:
      'Privater Chauffeurtransfer vom Wiener Stadtzentrum nach Bratislava — 80 km, etwa eine Stunde, Festpreis, kein Grenzstopp. Ideal für Geschäftstermine, Tagesausflüge und Fahrten von Hotel zu Hotel.',
  },
  {
    slug: 'vienna-to-budapest',
    from: 'Wien',
    to: 'Budapest',
    distance: '~245 km',
    driveTime: '~2 Std. 30 Min. – 3 Std.',
    routeDescription:
      'Südöstlich über die A4-Autobahn zur ungarischen Grenze bei Hegyeshalom, weiter auf der M15/M1 nach Budapest.',
    whyBook: [
      'Direkte Alternative zu Anschlussflug oder Zugumstieg',
      'Ein lizenzierter Fahrer die gesamte Strecke, inklusive Grenzübertritt',
      'Komfortabel für Geschäftsreisen oder Wochenendtrips zwischen den beiden Hauptstädten',
    ],
    crossBorder: true,
  },
  {
    slug: 'salzburg-to-munich',
    from: 'Salzburg',
    to: 'München',
    distance: '~145 km',
    driveTime: '~1 Std. 30 Min.',
    routeDescription: 'Eine kurze grenzüberschreitende Fahrt nordwärts auf der deutschen A8 — eine der meistgebuchten internationalen Strecken ab Salzburg.',
    whyBook: [
      'Beliebt für Anschlüsse zum Flughafen München (MUC) für Weiterflüge',
      'Keine separate Buchung eines grenzüberschreitenden Taxis nötig',
      'Festpreis im Voraus vereinbart, unabhängig vom Grenzverkehr',
    ],
    crossBorder: true,
  },
  {
    slug: 'innsbruck-airport-to-kitzbuehel',
    from: 'Flughafen Innsbruck (INN)',
    to: 'Kitzbühel',
    distance: '~90 km',
    driveTime: '~1 Std.',
    routeDescription: 'Ostwärts auf der A12 Inntalautobahn, dann über die B170/B161 nach Kitzbühel — die direkteste Flughafen-zu-Resort-Strecke der Region.',
    whyBook: [
      'Winterfeste Fahrzeuge mit Platz für Ski und Snowboards',
      'Direkt zu Ihrem Chalet oder Hotel, kein Shuttlebus-Transfer',
      'Die kürzeste Flughafen-zu-Resort-Fahrzeit unter den großen Tiroler Skiorten',
    ],
  },
  {
    slug: 'innsbruck-airport-to-st-anton',
    from: 'Flughafen Innsbruck (INN)',
    to: 'St. Anton am Arlberg',
    distance: '~100 km',
    driveTime: '~1 Std. 10 Min.',
    routeDescription: 'Westlich auf der A12 Inntalautobahn und der S16 Arlberg Schnellstraße direkt nach St. Anton.',
    whyBook: [
      'Direkter Transfer mit Allradfahrzeug zu Ihrem Arlberg-Chalet',
      'Geräumige Vans für Skiausrüstung und großes Gepäck',
      'Flugverfolgung und Fahrerempfang direkt in der Ankunftshalle des Flughafens Innsbruck',
    ],
  },
  {
    slug: 'innsbruck-airport-to-ischgl',
    from: 'Flughafen Innsbruck (INN)',
    to: 'Ischgl',
    distance: '~100 km',
    driveTime: '~1 Std. 15 Min.',
    routeDescription: 'Westlich über die A12 Inntalautobahn und die B188 Silvrettastraße das Paznauntal hinauf nach Ischgl.',
    whyBook: [
      'Ruhiger Transfer durchs Paznauntal mit erfahrenen Alpenfahrern',
      'Fester, transparenter Preis ohne versteckte Bergmautzuschläge',
      'Komfortable Fahrzeuge, ausgestattet für winterliche Schneeverhältnisse',
    ],
  },
  {
    slug: 'innsbruck-airport-to-soelden',
    from: 'Flughafen Innsbruck (INN)',
    to: 'Sölden',
    distance: '~85 km',
    driveTime: '~1 Std. 10 Min.',
    routeDescription: 'Westlich auf der A12 bis zur Ausfahrt Ötztal, dann südlich auf der B186 Ötztaler Straße nach Sölden.',
    whyBook: [
      'Schnellster privater Transfer vom Flughafen Innsbruck ins Gletschergebiet Ötztal',
      'Direkt zu den Hotels in Sölden und zur „007 Elements“-Basis',
      'Alles inklusive zum Festpreis, mit Überwachung von Flugverspätungen',
    ],
  },
  {
    slug: 'innsbruck-airport-to-mayrhofen',
    from: 'Flughafen Innsbruck (INN)',
    to: 'Mayrhofen',
    distance: '~75 km',
    driveTime: '~1 Std.',
    routeDescription: 'Östlich auf der A12 Inntalautobahn, Ausfahrt Zillertal auf die B169 direkt nach Mayrhofen.',
    whyBook: [
      'Direkter Transfer ins Zillertal, ganz ohne Zugumstieg',
      'Winterfeste Fahrzeuge für Besucher des Hintertuxer Gletschers',
      'Persönliche Abholung direkt vor der Ankunftshalle in Innsbruck',
    ],
  },
  {
    slug: 'innsbruck-airport-to-lech',
    from: 'Flughafen Innsbruck (INN)',
    to: 'Lech am Arlberg',
    distance: '~120 km',
    driveTime: '~1 Std. 30 Min.',
    routeDescription: 'Westlich über die A12 und die S16 durch den Arlbergpass oder den Flexenpass-Tunnel nach Lech.',
    whyBook: [
      'Exklusiver VIP-Transfer zu luxuriösen 5-Sterne-Hotels am Arlberg',
      'Professionelle Chauffeure mit Erfahrung im winterlichen Passverkehr',
      'Geräumige V-Klasse- und S-Klasse-Fahrzeuge verfügbar',
    ],
  },
  {
    slug: 'salzburg-airport-to-kitzbuehel',
    from: 'Flughafen Salzburg (SZG)',
    to: 'Kitzbühel',
    distance: '~75 km',
    driveTime: '~1 Std. 15 Min.',
    routeDescription: 'Südwestlich über die Loferer Straße (B178) durch Unken und Waidring nach Kitzbühel.',
    whyBook: [
      'Beliebte Skiroute für Charterflüge am Flughafen Salzburg',
      'Komfortabler Tür-zu-Tür-Service direkt zu den Chalets in Kitzbühel',
      'Kein mühsames Schleppen schwerer Skitaschen im Regionalverkehr',
    ],
  },
  {
    slug: 'salzburg-airport-to-zell-am-see',
    from: 'Flughafen Salzburg (SZG)',
    to: 'Zell am See',
    distance: '~80 km',
    driveTime: '~1 Std. 15 Min.',
    routeDescription: 'Südlich über die A10 Tauernautobahn oder die B311 Pinzgauer Straße nach Zell am See.',
    whyBook: [
      'Direkter Transfer ans Seeufer und zum Gletscherresort Kaprun',
      'Festpreis inklusive Gepäck, Skiausrüstung und Mautgebühren',
      'Rund um die Uhr verfügbar, auch für frühe Charterflug-Ankünfte',
    ],
  },
  {
    slug: 'salzburg-airport-to-saalbach',
    from: 'Flughafen Salzburg (SZG)',
    to: 'Saalbach-Hinterglemm',
    distance: '~85 km',
    driveTime: '~1 Std. 20 Min.',
    routeDescription: 'Südwestlich über die B178 und die B311 ins Glemmtal Richtung Saalbach.',
    whyBook: [
      'Unkomplizierte Anreise ins Skicircus-Skigebiet',
      'Geräumige Kleinbusse und Mercedes V-Klasse für Gruppen und Familien',
      'Direkte Ablieferung vor Ihrer Hoteltür',
    ],
  },
  {
    slug: 'salzburg-airport-to-bad-gastein',
    from: 'Flughafen Salzburg (SZG)',
    to: 'Bad Gastein',
    distance: '~95 km',
    driveTime: '~1 Std. 15 Min.',
    routeDescription: 'Südlich über die A10 Tauernautobahn und die B167 das Gasteinertal hinauf nach Bad Gastein.',
    whyBook: [
      'Landschaftlich reizvolle Fahrt direkt zu den historischen Belle-Époque-Spahotels',
      'Komfortabel für Wintersportler und Wellnessgäste im Sommer gleichermaßen',
      'Fester, transparenter Preis inklusive Überwachung von Flugverspätungen',
    ],
  },
  {
    slug: 'munich-airport-to-innsbruck',
    from: 'Flughafen München (MUC)',
    to: 'Innsbruck',
    distance: '~160 km',
    driveTime: '~2 Std.',
    routeDescription: 'Südlich über die deutschen Autobahnen A9 und A8, Grenzübertritt nach Österreich über die A93/A12 Inntalautobahn nach Innsbruck.',
    whyBook: [
      'Nahtloser grenzüberschreitender Transfer vom größten Langstrecken-Drehkreuz Deutschlands',
      'Kein Umstieg mit schwerem Gepäck am Münchner Hauptbahnhof',
      'Lizenzierte grenzüberschreitende Chauffeure zum Festpreis',
    ],
    crossBorder: true,
  },
  {
    slug: 'munich-airport-to-salzburg',
    from: 'Flughafen München (MUC)',
    to: 'Salzburg',
    distance: '~170 km',
    driveTime: '~1 Std. 45 Min.',
    routeDescription: 'Östlich über die deutschen Autobahnen A92 und A8, Grenzübertritt bei Walserberg direkt nach Salzburg.',
    whyBook: [
      'Direkte Verbindung zwischen Langstreckenflügen ab München und der Salzburger Altstadt',
      'Keine Verspätungen der Deutschen Bahn oder Rückgabegebühren für Mietwagen',
      'Professioneller Empfangsservice in Terminal 1 oder 2 des Flughafens München',
    ],
    crossBorder: true,
  },
  {
    slug: 'munich-airport-to-kitzbuehel',
    from: 'Flughafen München (MUC)',
    to: 'Kitzbühel',
    distance: '~165 km',
    driveTime: '~2 Std.',
    routeDescription: 'Südlich über die A8 Richtung Inntaldreieck, weiter über die A93/B173 durch Kufstein nach Kitzbühel.',
    whyBook: [
      'Erste Wahl für internationale Langstreckenreisende nach Kitzbühel',
      'Allradfahrzeuge für winterliche Schneeverhältnisse zwischen Bayern und Tirol',
      'Ein Fahrzeug und ein Fahrer Tür zu Tür, ohne Verzögerungen an der Grenze',
    ],
    crossBorder: true,
  },
  {
    slug: 'munich-airport-to-st-anton',
    from: 'Flughafen München (MUC)',
    to: 'St. Anton am Arlberg',
    distance: '~240 km',
    driveTime: '~2 Std. 45 Min.',
    routeDescription: 'Südlich über die A95 oder A8/A12 durch das Inntal zum Arlberg.',
    whyBook: [
      'Direkter Executive-Transfer für internationale Gäste ab München',
      'Geräumige V-Klasse- und SUV-Flotte für Skigepäck',
      'Alle Grenzvignetten und Mautgebühren im Festpreis inbegriffen',
    ],
    crossBorder: true,
  },
  {
    slug: 'zurich-airport-to-lech',
    from: 'Flughafen Zürich (ZRH)',
    to: 'Lech am Arlberg',
    distance: '~195 km',
    driveTime: '~2 Std. 15 Min.',
    routeDescription: 'Östlich über die Schweizer Autobahnen A1/A3, vorbei am Walensee, Grenzübertritt bei Feldkirch nach Lech.',
    whyBook: [
      'Die führende Luxustransferroute von Zürich zu den 5-Sterne-Resorts am Arlberg',
      'Lizenziert für schweizerisch-österreichische internationale Chauffeurtransfers',
      'Diskreter Executive-Service für anspruchsvolle Reisende',
    ],
    crossBorder: true,
  },
  {
    slug: 'zurich-airport-to-st-anton',
    from: 'Flughafen Zürich (ZRH)',
    to: 'St. Anton am Arlberg',
    distance: '~200 km',
    driveTime: '~2 Std. 15 Min.',
    routeDescription: 'Östlich durch die Schweiz über die A3/A13, Einreise nach Vorarlberg/Tirol über den Arlbergpass oder -tunnel.',
    whyBook: [
      'Bevorzugte Route für internationale Ankünfte über Zürich-Kloten',
      'Geräumige Mercedes-Vans für Familien und Skiausrüstung',
      'Fester grenzüberschreitender Preis ohne versteckte Kosten',
    ],
    crossBorder: true,
  },
  {
    slug: 'vienna-airport-to-bratislava',
    from: 'Flughafen Wien (VIE)',
    to: 'Bratislava',
    distance: '~65 km',
    driveTime: '~45 Min.',
    routeDescription: 'Östlich über die Autobahnen A4 und A6 durch Kittsee über die Grenze nach Bratislava — in beide Richtungen buchbar, Ankunft oder Abfahrt.',
    whyBook: [
      'Kürzester Hauptstadt-zu-Hauptstadt-Transfer Mitteleuropas',
      'Deckt beide Richtungen ab — Ankünfte am Flughafen Wien mit Ziel Slowakei und Abfahrten aus Bratislava zu einem Flug ab Wien',
      'Schnell, direkt und zum Festpreis, Tür zu Tür',
    ],
    crossBorder: true,
    seoTitle: 'Flughafen Wien nach Bratislava Transfer | 45 Minuten, Festpreis',
    seoDescription:
      'Privater Transfer zwischen Flughafen Wien und Bratislava — 65 km, ca. 45 Minuten, Festpreis Tür zu Tür. Deckt sowohl Ankünfte am Flughafen Wien als auch Abfahrten aus Bratislava ab.',
  },
  {
    slug: 'vienna-airport-to-budapest',
    from: 'Flughafen Wien (VIE)',
    to: 'Budapest',
    distance: '~230 km',
    driveTime: '~2 Std. 15 Min.',
    routeDescription: 'Südöstlich über die A4-Autobahn und die ungarische Autobahn M1 direkt nach Budapest.',
    whyBook: [
      'Stark nachgefragter Langstreckentransfer vom Flughafen direkt in die Hauptstadt',
      'Kein Umsteigen am Flughafen oder Bahnhofstransfer nötig',
      'Professioneller, zweisprachiger Fahrer mit Erfahrung auf internationalen Strecken',
    ],
    crossBorder: true,
  },
  {
    slug: 'vienna-airport-to-hallstatt',
    from: 'Flughafen Wien (VIE)',
    to: 'Hallstatt',
    distance: '~300 km',
    driveTime: '~3 Std. 15 Min.',
    routeDescription: 'Westlich auf der A1 Westautobahn bis zur Ausfahrt Regau, weiter über Gmunden und Bad Ischl nach Hallstatt.',
    whyBook: [
      'Direkter Transfer vom Flughafen Wien zum UNESCO-Welterbeort Hallstatt',
      'Kein umständliches Umsteigen zwischen Zug und Fähre mit Gepäck',
      'Optionale landschaftliche Zwischenstopps im Salzkammergut',
    ],
  },
  {
    slug: 'salzburg-to-hallstatt',
    from: 'Salzburg',
    to: 'Hallstatt',
    distance: '~75 km',
    driveTime: '~1 Std. 15 Min.',
    routeDescription: 'Östlich über die Wolfgangsee-Straße (B158) durch Fuschl und St. Gilgen, dann auf der B145 nach Hallstatt.',
    whyBook: [
      'Die beliebteste Tagesausflugs- und Privattransferroute ab Salzburg',
      'Landschaftlich beeindruckende Fahrt vorbei am Fuschlsee und Wolfgangsee',
      'Flexible Abfahrtszeiten, abgestimmt auf Ihren Reiseplan',
    ],
  },
  {
    slug: 'salzburg-airport-to-schladming',
    from: 'Flughafen Salzburg (SZG)',
    to: 'Schladming',
    distance: '~90 km',
    driveTime: '~1 Std.',
    routeDescription: 'Südlich über die A10 Tauernautobahn und die B320 Ennstal Straße direkt nach Schladming.',
    whyBook: [
      'Schnellste Anbindung an die Planai und das Ski-Amadé-4-Berge-Skigebiet',
      'Festpreis inklusive Tauernautobahn-Mautgebühren',
      'Direkte Ablieferung am Hotel, ohne Skiausrüstung im Zug zu transportieren',
    ],
  },
  {
    slug: 'salzburg-airport-to-obertauern',
    from: 'Flughafen Salzburg (SZG)',
    to: 'Obertauern',
    distance: '~90 km',
    driveTime: '~1 Std. 10 Min.',
    routeDescription: 'Südlich über die A10 Tauernautobahn bis zur Ausfahrt Radstadt, dann auf der B99 Radstädter Tauernstraße nach Obertauern.',
    whyBook: [
      'Direkter Transfer zum schneesicheren Passresort in Höhenlage',
      'Allradfahrzeuge mit Erfahrung im winterlichen Bergverkehr',
      'Alles inklusive zum Festpreis, mit Überwachung von Flugverspätungen',
    ],
  },
  {
    slug: 'munich-airport-to-saalbach',
    from: 'Flughafen München (MUC)',
    to: 'Saalbach-Hinterglemm',
    distance: '~215 km',
    driveTime: '~2 Std. 30 Min.',
    routeDescription: 'Südlich über die deutsche A8, Grenzübertritt bei Siegsdorf/Lofer (B178) ins Glemmtal.',
    whyBook: [
      'Beliebter internationaler Langstreckentransfer für Skifahrer aus Großbritannien und Skandinavien',
      'Große Mercedes-V-Klasse-Vans für Gruppen mit viel Skigepäck',
      'Keine Grenzformalitäten oder Sorgen um die Autobahnvignette',
    ],
    crossBorder: true,
  },
  {
    slug: 'munich-airport-to-zell-am-see',
    from: 'Flughafen München (MUC)',
    to: 'Zell am See',
    distance: '~200 km',
    driveTime: '~2 Std. 15 Min.',
    routeDescription: 'Südlich über die A8 und die B311 Pinzgauer Straße direkt zum Zeller See.',
    whyBook: [
      'Direkter Transfer für Langstreckenankünfte in München mit Ziel Zell am See und Gletscher Kaprun',
      'Fester, transparenter Preis, im Voraus vereinbart',
      'Vollständige Flugverfolgung und Empfang in der Ankunftshalle',
    ],
    crossBorder: true,
  },
  {
    slug: 'munich-airport-to-mayrhofen',
    from: 'Flughafen München (MUC)',
    to: 'Mayrhofen',
    distance: '~190 km',
    driveTime: '~2 Std. 15 Min.',
    routeDescription: 'Südlich über die A8 und den A93/A12-Inntalkorridor, Ausfahrt Zillertal (B169) nach Mayrhofen.',
    whyBook: [
      'Direkter Chauffeurtransfer ab München ins Zillertal',
      'Geräumige Fahrzeuge für Gletscher-Skiausrüstung',
      'Komfortable Tür-zu-Tür-Fahrt ohne überfüllte Münchner Züge',
    ],
    crossBorder: true,
  },
  {
    slug: 'munich-airport-to-soelden',
    from: 'Flughafen München (MUC)',
    to: 'Sölden',
    distance: '~240 km',
    driveTime: '~2 Std. 45 Min.',
    routeDescription: 'Südlich über das deutsche Autobahnnetz und die A12/B186 ins Ötztal.',
    whyBook: [
      'Zuverlässiger grenzüberschreitender Transfer für internationale Langstreckengäste',
      'Alle Mautgebühren und Vignetten im Festpreis inbegriffen',
      'Allrad-Mercedes-Fahrzeuge, geeignet für winterliche Alpenstraßen',
    ],
    crossBorder: true,
  },
  {
    slug: 'zurich-airport-to-ischgl',
    from: 'Flughafen Zürich (ZRH)',
    to: 'Ischgl',
    distance: '~235 km',
    driveTime: '~2 Std. 30 Min.',
    routeDescription: 'Östlich über die Schweizer Autobahnen A3/A13, Einreise nach Österreich bei Feldkirch auf die S16/B188 ins Paznauntal.',
    whyBook: [
      'Exklusiver VIP-Transfer für grenzüberschreitende Ankünfte aus Zürich',
      'Erfahrene schweizerisch-österreichische Grenz-Chauffeure',
      'Diskretes und komfortables Executive-Reisen',
    ],
    crossBorder: true,
  },
  {
    slug: 'graz-to-ljubljana',
    from: 'Graz',
    to: 'Ljubljana',
    distance: '~195 km',
    driveTime: '~2 Std.',
    routeDescription: 'Südlich über die A2 Süd Autobahn durch den Grenzübergang Spielfeld nach Slowenien auf die Autobahn A1.',
    whyBook: [
      'Nahtlose regionale grenzüberschreitende Verbindung zwischen der Steiermark und Slowenien',
      'Ideal für Geschäftsreisen und diplomatische Fahrten',
      'Festpreis inklusive slowenischer Autobahnvignette',
    ],
    crossBorder: true,
  },
  {
    slug: 'graz-to-venice',
    from: 'Graz',
    to: 'Venedig',
    distance: '~380 km',
    driveTime: '~3 Std. 45 Min.',
    routeDescription: 'Südwestlich über die A2 Süd Autobahn, Grenzübertritt bei Tarvisio nach Italien auf die A23/A4 nach Venedig.',
    whyBook: [
      'Exklusiver privater Intercity-Transfer in die venezianische Lagune (Piazzale Roma)',
      'Komfortable Langstreckenfahrt in Mercedes-Limousine oder -Van',
      'Flexible Zwischenstopps in Kärnten oder Friaul möglich',
    ],
    crossBorder: true,
  },
  {
    slug: 'klagenfurt-to-ljubljana',
    from: 'Klagenfurt',
    to: 'Ljubljana',
    distance: '~85 km',
    driveTime: '~1 Std.',
    routeDescription: 'Südlich über die B91 Loiblpass-Straße oder die A11 durch den Karawankentunnel direkt nach Slowenien.',
    whyBook: [
      'Schnellster grenzüberschreitender Transfer zwischen Kärnten und Ljubljana',
      'Mautgebühren für den Karawankentunnel im Festpreis inbegriffen',
      'Tür-zu-Tür-Transfer für Hotel- und Geschäftstermine',
    ],
    crossBorder: true,
  },
  {
    slug: 'klagenfurt-to-venice',
    from: 'Klagenfurt',
    to: 'Venedig',
    distance: '~280 km',
    driveTime: '~2 Std. 45 Min.',
    routeDescription: 'Südwestlich über die A2 Süd Autobahn über die italienische Grenze bei Udine (A23) nach Venedig.',
    whyBook: [
      'Direkter Luxustransfer von den Alpen an die Adria',
      'Kein Zugumstieg mit schwerem Kreuzfahrt- oder Urlaubsgepäck',
      'Lizenziert für internationale Abholungen und Ablieferungen in Italien',
    ],
    crossBorder: true,
  },
  {
    slug: 'vienna-to-prague',
    from: 'Wien',
    to: 'Prag',
    distance: '~310 km',
    driveTime: '~3 Std. 15 Min.',
    routeDescription: 'Nördlich über die A5 Weinviertel Autobahn nach Tschechien über Mikulov auf der D52/D1 nach Prag.',
    whyBook: [
      'Erstklassiger Hauptstadt-zu-Hauptstadt-Transfer in Mitteleuropa',
      'Direkte Abholung an Wiener Hotels bis zur Prager Burg oder Altstadt',
      'Alle tschechischen Autobahnvignetten-Gebühren inbegriffen',
    ],
    crossBorder: true,
  },
  {
    slug: 'salzburg-to-graz',
    from: 'Salzburg',
    to: 'Graz',
    distance: '~280 km',
    driveTime: '~2 Std. 45 Min.',
    routeDescription: 'Südöstlich über die A10 Tauernautobahn und die A9 Pyhrn Autobahn durchs Ennstal.',
    whyBook: [
      'Verbindet Österreichs führende Festspielstadt mit der steirischen Landeshauptstadt',
      'Komfortabler Intercity-Transfer ohne Umsteigen im Regionalzug',
      'Festpreis inklusive Bergtunnel-Mautgebühren',
    ],
  },
  {
    slug: 'bregenz-to-zurich-airport',
    from: 'Bregenz',
    to: 'Flughafen Zürich (ZRH)',
    distance: '~120 km',
    driveTime: '~1 Std. 15 Min.',
    routeDescription: 'Westlich über die Schweizer Grenze (Höchst/St. Margrethen) auf der Schweizer Autobahn A1 nach Zürich-Kloten.',
    whyBook: [
      'Wichtigste Flughafenanbindung für Vorarlberger Privat- und Geschäftsreisende',
      'Grenzüberschreitender lizenzierter Fahrer, Schweizer Vignette inbegriffen',
      'Pünktliche Flughafentransfers mit Flugverfolgung',
    ],
    crossBorder: true,
  },
  {
    slug: 'innsbruck-to-zurich',
    from: 'Innsbruck',
    to: 'Zürich',
    distance: '~290 km',
    driveTime: '~3 Std.',
    routeDescription: 'Westlich über die A12/S16 durch den Arlberg, Grenzübertritt über Liechtenstein/Schweiz auf der A3 nach Zürich.',
    whyBook: [
      'Direkter Stadt-zu-Stadt-Transfer zwischen Tirol und dem Finanzplatz Zürich',
      'Komfortable Executive-Fahrt mit optionalen Zwischenstopps in Vaduz oder Bregenz',
      'Festpreis inklusive aller internationalen Transitgebühren',
    ],
    crossBorder: true,
  },
  {
    slug: 'vienna-to-wachau',
    from: 'Wien',
    to: 'Wachau-Tal',
    distance: '~85 km',
    driveTime: '~1 Std.',
    routeDescription: 'Westlich über die A1 und die S33 nach Krems und ins malerische Donau-Weinbaugebiet (Dürnstein/Melk).',
    whyBook: [
      'Privater Tagesausflugs- und Weinverkostungstransfer mit persönlichem Fahrer',
      'Flexibler Reiseplan mit Stopps bei Stift Melk und Weingütern',
      'Fester Tages- oder Transferpreis',
    ],
  },
  {
    slug: 'vienna-to-baden-wien',
    from: 'Wien',
    to: 'Baden bei Wien',
    distance: '~30 km',
    driveTime: '~35 Min.',
    routeDescription: 'Südlich über die A2 Süd Autobahn direkt in den Kurort Baden.',
    whyBook: [
      'Schneller Executive-Transfer zur Therme und zum Casino Baden',
      'Ideal für Hotelgäste, abendliche Casinobesuche und Wellness-Aufenthalte',
      'Festpreis, Tür zu Tür',
    ],
  },
  {
    slug: 'bregenz-to-lech',
    from: 'Bregenz',
    to: 'Lech am Arlberg',
    distance: '~95 km',
    driveTime: '~1 Std. 15 Min.',
    routeDescription: 'Südöstlich über die Rheintal Autobahn A14 und die B197 über den Flexenpass nach Lech.',
    whyBook: [
      'Direkte Verbindung vom Vorarlberger Rheintal zum Luxusresort am Arlberg',
      'Erfahrene Bergchauffeure für starke winterliche Schneefälle',
      'Geräumige Luxus-Vans der V-Klasse für Familien und Skiausrüstung',
    ],
  },
  {
    slug: 'bregenz-to-st-anton',
    from: 'Bregenz',
    to: 'St. Anton am Arlberg',
    distance: '~105 km',
    driveTime: '~1 Std. 20 Min.',
    routeDescription: 'Südöstlich über die A14 und die S16 Arlberg Schnellstraße nach St. Anton.',
    whyBook: [
      'Schneller, direkter Transfer zwischen dem Bodensee und dem Skigebiet Arlberg',
      'Alle Bergtunnel-Mautgebühren inbegriffen',
      'Festpreis mit professionellem Chauffeur',
    ],
  },
  {
    slug: 'linz-to-salzburg',
    from: 'Linz',
    to: 'Salzburg',
    distance: '~130 km',
    driveTime: '~1 Std. 25 Min.',
    routeDescription: 'Westlich auf der A1 Westautobahn, die Oberösterreich mit dem Land Salzburg verbindet.',
    whyBook: [
      'Häufig gebuchter Intercity-Transfer für Geschäfts- und Urlaubsreisende',
      'Kein Bahnhofsumstieg mit schwerem Gepäck nötig',
      'Direkt zum Hotel oder Anschluss an den Flughafen Linz/Salzburg',
    ],
  },
  {
    slug: 'villach-to-venice',
    from: 'Villach',
    to: 'Venedig',
    distance: '~240 km',
    driveTime: '~2 Std. 30 Min.',
    routeDescription: 'Südwestlich über die A2 Süd Autobahn über die italienische Grenze bei Tarvisio via Udine (A23/A4) nach Venedig.',
    whyBook: [
      'Kürzeste Luxus-Grenzfahrt von Kärnten an die venezianische Küste',
      'Direkte Ablieferung am Piazzale Roma oder Kreuzfahrtterminal Venedig',
      'Lizenziert für internationale Abholungen und Ablieferungen in Italien',
    ],
    crossBorder: true,
  },
  {
    slug: 'villach-to-ljubljana',
    from: 'Villach',
    to: 'Ljubljana',
    distance: '~100 km',
    driveTime: '~1 Std.',
    routeDescription: 'Südlich über die A11 durch den Karawankentunnel direkt nach Slowenien nach Ljubljana.',
    whyBook: [
      'Schnellste grenzüberschreitende Verbindung zwischen Kärnten und Flughafen/Stadt Ljubljana',
      'Tunnelmaut und slowenische Autobahnvignette inbegriffen',
      'Rund um die Uhr als Privattransfer verfügbar',
    ],
    crossBorder: true,
  },
  {
    slug: 'salzburg-airport-to-berchtesgaden',
    from: 'Flughafen Salzburg (SZG)',
    to: 'Berchtesgaden',
    distance: '~30 km',
    driveTime: '~35 Min.',
    routeDescription:
      'Eine kurze grenzüberschreitende Fahrt südwestlich auf der B305/B20, Grenzübertritt nach Bayern bei Hangender Stein, direkt weiter nach Berchtesgaden.',
    whyBook: [
      'Einer der kürzesten Flughafentransfers im Netzwerk, ideal für einen Tagesausflug zum Kehlsteinhaus oder Königssee',
      'Kein Mietwagen oder lokale Busverbindungen für einen Tagesausflug über die Grenze nötig',
      'Festpreis inklusive Grenzübertritt',
    ],
    crossBorder: true,
  },
  {
    slug: 'salzburg-airport-to-hallstatt',
    from: 'Flughafen Salzburg (SZG)',
    to: 'Hallstatt',
    distance: '~75 km',
    driveTime: '~1 Std. 15 Min.',
    routeDescription:
      'Östlich über die Wolfgangsee-Straße (B158) durch Fuschl und St. Gilgen, dann auf der B145 nach Hallstatt — dieselbe malerische Salzkammergut-Route wie ab der Salzburger Innenstadt.',
    whyBook: [
      'Direkt von der Ankunft zum UNESCO-Seeort, ohne vorherigen Umstieg auf Zug oder Bus in der Salzburger Innenstadt',
      'Nützlich für Gäste, die für einen Ein-Tages-Besuch in Hallstatt einfliegen, bevor es weitergeht',
      'Festpreis inklusive Flugverfolgung',
    ],
  },
  {
    slug: 'vienna-airport-to-linz',
    from: 'Flughafen Wien (VIE)',
    to: 'Linz',
    distance: '~185 km',
    driveTime: '~1 Std. 45 Min. – 2 Std.',
    routeDescription:
      'Westlich auf der A1 Westautobahn entlang des Donaukorridors, derselben Route wie im Verkehr zwischen Wien und Salzburg, mit Ziel Linz.',
    whyBook: [
      'Kein Umstieg mit Gepäck am Wiener Hauptbahnhof',
      'Nützlich, wenn der Flughafen Linz keine passende Verbindung von Ihrem Startort bietet',
      'Festpreis vor Fahrtantritt vereinbart',
    ],
  },
  {
    slug: 'vienna-airport-to-wachau',
    from: 'Flughafen Wien (VIE)',
    to: 'Wachau-Tal',
    distance: '~100 km',
    driveTime: '~1 Std. 10 Min.',
    routeDescription:
      'Westlich über die A1 und die S33 nach Krems, am östlichen Rand des Donau-Weinbaugebiets — derselbe Korridor wie bei der Stadt-zu-Stadt-Strecke Wien–Wachau.',
    whyBook: [
      'Direkt von der Ankunft zum Hotel oder Weingut in der Wachau, ohne Umstieg in der Wiener Innenstadt',
      'Nützlich für weintouristische Ankünfte mit Ziel Dürnstein oder Krems',
      'Flexible Zwischenstopps auf Anfrage',
    ],
  },
  {
    slug: 'vienna-airport-to-baden-wien',
    from: 'Flughafen Wien (VIE)',
    to: 'Baden bei Wien',
    distance: '~40 km',
    driveTime: '~35 Min.',
    routeDescription:
      'Südlich über die A4 und die A2 Südautobahn, an der Wiener Innenstadt vorbei, direkt in den Kurort Baden.',
    whyBook: [
      'Schneller, direkter Ankunftstransfer zu den Thermen und dem Casino Baden',
      'Kein Umstieg von Zug auf Taxi über Wien Meidling',
      'Festpreis, Tür zu Tür',
    ],
  },
  {
    slug: 'salzburg-airport-to-innsbruck',
    from: 'Flughafen Salzburg (SZG)',
    to: 'Innsbruck',
    distance: '~140–200 km',
    driveTime: '~1 Std. 45 Min. – 2 Std. 15 Min.',
    routeDescription:
      'Die schnellste Route führt kurz über die deutsche A8 durch Bayern, bevor sie bei Kufstein wieder auf die A12 wechselt — derselbe Abkürzungsweg wie auf der Stadt-zu-Stadt-Strecke Salzburg–Innsbruck.',
    whyBook: [
      'Ein Fahrzeug die ganze Strecke, inklusive des kurzen deutschen Grenzübertritts',
      'Kein Inlandsflug zwischen den beiden Städten nötig',
      'Beliebt für regionsübergreifende Ankünfte mit Ziel Tirol',
    ],
    crossBorder: true,
  },
  {
    slug: 'salzburg-airport-to-munich',
    from: 'Flughafen Salzburg (SZG)',
    to: 'München',
    distance: '~145 km',
    driveTime: '~1 Std. 30 Min.',
    routeDescription:
      'Nordwärts auf der deutschen A8 — eine kurze grenzüberschreitende Fahrt für Reisende mit Anschlussflug ab München oder Ziel Stadt München.',
    whyBook: [
      'Beliebt für internationale Anschlüsse über den Flughafen München (MUC)',
      'Keine separate Buchung eines grenzüberschreitenden Taxis ab Salzburg nötig',
      'Festpreis im Voraus vereinbart, unabhängig vom Grenzverkehr',
    ],
    crossBorder: true,
  },
  {
    slug: 'innsbruck-airport-to-seefeld',
    from: 'Flughafen Innsbruck (INN)',
    to: 'Seefeld in Tirol',
    distance: '~25 km',
    driveTime: '~25 Min.',
    routeDescription:
      'Nördlich über die B177 Zirler-Berg-Straße, hinauf aus dem Inntal auf das Seefelder Plateau — einer der kürzesten Flughafen-zu-Resort-Wege Österreichs.',
    whyBook: [
      'Der kürzeste Flughafentransfer unter den großen Tiroler Skiorten',
      'Direkt zu den Hotels in Seefeld, ohne Regionalzug oder Ortsshuttle',
      'Gut geeignet für das autofreie Fußgängerzentrum des Orts',
    ],
  },
  {
    slug: 'innsbruck-airport-to-serfaus-fiss-ladis',
    from: 'Flughafen Innsbruck (INN)',
    to: 'Serfaus-Fiss-Ladis',
    distance: '~85 km',
    driveTime: '~1 Std. 15 Min.',
    routeDescription:
      'Westlich auf der A12 Inntalautobahn Richtung Landeck, dann südlich hinauf auf das Serfaus-Fiss-Ladis-Plateau über dem Tal.',
    whyBook: [
      'Direkt zu den Plateau-Orten, ohne die Seilbahnverbindung, die manche Reisende vom Talboden nutzen',
      'Familienfreundliches Resort mit Platz für das Gepäck und die Ausrüstung größerer Gruppen',
      'Fester, transparenter Preis vor Fahrtantritt vereinbart',
    ],
  },
  {
    slug: 'linz-airport-to-hallstatt',
    from: 'Flughafen Linz (LNZ)',
    to: 'Hallstatt',
    distance: '~80 km',
    driveTime: '~1 Std. 15 Min.',
    routeDescription: 'Südlich über die A1 und die B145 durch das Salzkammergut nach Hallstatt.',
    whyBook: [
      'Direkt von der Ankunft zum UNESCO-Ort, kein umständliches Umsteigen zwischen Zug und Fähre mit Gepäck',
      'Nützlich für Reisende, die den Flughafen Linz als ruhigere Alternative zu Salzburg oder Wien nutzen',
      'Festpreis inklusive Flugverfolgung',
    ],
  },
  {
    slug: 'klagenfurt-airport-to-villach',
    from: 'Flughafen Klagenfurt (KLU)',
    to: 'Villach',
    distance: '~40 km',
    driveTime: '~30 Min.',
    routeDescription: 'Westlich auf der A2 Südautobahn, eine kurze und direkte Fahrt durch die Kärntner Seenlandschaft.',
    whyBook: [
      'Kurzer, häufig gebuchter Transfer zwischen Kärntens zwei größten Städten',
      'Nützlich als Verbindung vor einer Weiterreise nach Italien oder Slowenien',
      'Festpreis, Tür zu Tür',
    ],
  },
  {
    slug: 'vienna-to-hallstatt',
    from: 'Wien',
    to: 'Hallstatt',
    distance: '~280 km',
    driveTime: '~3 Std.',
    routeDescription: 'Westlich auf der A1 Westautobahn ins Salzkammergut, dann südlich auf der B145 durch Bad Ischl nach Hallstatt.',
    whyBook: [
      'Eine lange, aber beliebte Tagesausflugsroute für internationale Gäste mit Standort Wien',
      'Ein Fahrzeug Tür zu Tür, ohne Umstieg zwischen Zug und Fähre zum Ort',
      'Flexible Zwischenstopps in Bad Ischl oder im Salzkammergut möglich',
    ],
  },
  {
    slug: 'salzburg-to-zell-am-see',
    from: 'Salzburg',
    to: 'Zell am See',
    distance: '~90 km',
    driveTime: '~1 Std.',
    routeDescription: 'Südlich über die A10 Tauernautobahn oder die B311 Pinzgauer Straße direkt ans Ufer des Zeller Sees.',
    whyBook: [
      'Beliebte Wochenendstrecke sowohl für Wintersport als auch für Sommerausflüge an den See',
      'Direkt zu den Hotels am Seeufer, kein Umstieg im Regionalzug',
      'Festpreis inklusive Autobahnmaut',
    ],
  },
  {
    slug: 'salzburg-to-kitzbuehel',
    from: 'Salzburg',
    to: 'Kitzbühel',
    distance: '~95 km',
    driveTime: '~1 Std. 15 Min.',
    routeDescription:
      'Südwestlich über die Loferer Straße (B178) durch Unken und Waidring nach Kitzbühel — derselbe Korridor wie ab dem Flughafen Salzburg.',
    whyBook: [
      'Direkter Stadt-zu-Resort-Transfer ohne Bahnhofsumstieg',
      'Komfortabel für Gruppen mit Ski- oder Golfausrüstung',
      'Festpreis vor Fahrtantritt vereinbart',
    ],
  },
  {
    slug: 'innsbruck-to-kitzbuehel',
    from: 'Innsbruck',
    to: 'Kitzbühel',
    distance: '~90 km',
    driveTime: '~1 Std.',
    routeDescription:
      'Östlich auf der A12 Inntalautobahn, dann über die B170/B161 nach Kitzbühel, dieselbe Route wie ab dem Flughafen Innsbruck.',
    whyBook: [
      'Direkte Stadt-zu-Resort-Verbindung quer durch Tirol',
      'Kein Shuttlebus- oder Regionalzugumstieg mit Skigepäck',
      'Festpreis unabhängig vom Verkehr',
    ],
  },
  {
    slug: 'innsbruck-to-st-anton',
    from: 'Innsbruck',
    to: 'St. Anton am Arlberg',
    distance: '~105 km',
    driveTime: '~1 Std. 15 Min.',
    routeDescription: 'Westlich über die A12 Inntalautobahn und die S16 Arlberg Schnellstraße direkt nach St. Anton.',
    whyBook: [
      'Direkter Stadt-zu-Resort-Transfer durch den Arlbergtunnel',
      'Geräumige Fahrzeuge für Skiausrüstung und mehrtägiges Gepäck',
      'Festpreis vor Fahrtantritt vereinbart',
    ],
  },
  {
    slug: 'innsbruck-to-mayrhofen',
    from: 'Innsbruck',
    to: 'Mayrhofen',
    distance: '~75 km',
    driveTime: '~1 Std.',
    routeDescription: 'Östlich über die A12 Inntalautobahn, Ausfahrt auf die B169 ins Zillertal nach Mayrhofen.',
    whyBook: [
      'Direkter Zillertal-Transfer ohne Regionalzugumstieg in Jenbach',
      'Beliebt für Wochenend- und Wochenskiurlaube ab Innsbruck',
      'Festpreis inklusive Autobahnmaut',
    ],
  },
  {
    slug: 'innsbruck-to-munich',
    from: 'Innsbruck',
    to: 'München',
    distance: '~165 km',
    driveTime: '~2 Std.',
    routeDescription: 'Nördlich über den A12/A93-Inntalkorridor, Grenzübertritt bei Kufstein auf die A8 nach München.',
    whyBook: [
      'Ein Fahrzeug die ganze Strecke, inklusive des deutschen Grenzübertritts',
      'Beliebt für internationale Anschlüsse über den Flughafen München',
      'Festpreis vor Fahrtantritt vereinbart, unabhängig vom Grenzverkehr',
    ],
    crossBorder: true,
  },
  {
    slug: 'innsbruck-to-bolzano',
    from: 'Innsbruck',
    to: 'Bozen',
    distance: '~210 km',
    driveTime: '~2 Std. 15 Min.',
    routeDescription:
      'Südlich über die A13 Brennerautobahn, Österreichs wichtigste Route nach Italien, über den Brennerpass nach Südtirol.',
    whyBook: [
      'Die Überquerung des Brennerpasses ist im Festpreis inbegriffen, inklusive italienischer Vignette',
      'Komfortabel für Geschäftsreisen oder einen landschaftlichen Ausflug in die Dolomiten',
      'Ein Fahrer und ein Fahrzeug die ganze Strecke, kein Bahnhofsumstieg in Bozen',
    ],
    crossBorder: true,
  },
  {
    slug: 'linz-to-prague',
    from: 'Linz',
    to: 'Prag',
    distance: '~215 km',
    driveTime: '~2 Std. 30 Min.',
    routeDescription: 'Nördlich über die A7 Mühlkreisautobahn, Grenzübertritt bei Wullowitz nach Tschechien auf der D3 Richtung Prag.',
    whyBook: [
      'Direkte Hauptstadtverbindung ohne Regionalzugumstieg am Linzer Hauptbahnhof',
      'Ein lizenzierter Fahrer für die gesamte grenzüberschreitende Fahrt',
      'Festpreis im Voraus vereinbart',
    ],
    crossBorder: true,
  },
  {
    slug: 'reutte-to-fuessen',
    from: 'Reutte',
    to: 'Füssen',
    distance: '~25 km',
    driveTime: '~25 Min.',
    routeDescription: 'Ein kurzer grenzüberschreitender Sprung auf der B179, Grenzübertritt nach Bayern direkt nördlich von Reutte nach Füssen.',
    whyBook: [
      'Der direkteste Weg zu Schloss Neuschwanstein und Schloss Hohenschwangau von der Tiroler Seite',
      'Kein Busfahrplan, auf den man für einen Tagesausflug zu den Schlössern Rücksicht nehmen muss',
      'Festpreis inklusive Grenzübertritt',
    ],
    crossBorder: true,
  },
  {
    slug: 'vienna-airport-to-eisenstadt',
    from: 'Flughafen Wien (VIE)',
    to: 'Eisenstadt',
    distance: '~60 km',
    driveTime: '~50 Min.',
    routeDescription: 'Südlich über die A6 und die B50, eine kurze Fahrt durch die Weinberge des Burgenlands in die Landeshauptstadt.',
    whyBook: [
      'Direkter Ankunftstransfer für Geschäftsreisen oder Weintourismus im Burgenland',
      'Keine regionale Busverbindung ab Wien nötig',
      'Festpreis vor Fahrtantritt vereinbart',
    ],
  },
  {
    slug: 'vienna-airport-to-st-poelten',
    from: 'Flughafen Wien (VIE)',
    to: 'St. Pölten',
    distance: '~75 km',
    driveTime: '~1 Std.',
    routeDescription: 'Westlich auf der A1 Westautobahn, an der Wiener Innenstadt vorbei, direkt in die niederösterreichische Landeshauptstadt.',
    whyBook: [
      'Nützlich für Behörden- und Geschäftsreisen ohne Zugumstieg in Wien',
      'Direkt zu Büros oder Hotels in St. Pölten',
      'Festpreis unabhängig vom Verkehr',
    ],
  },
  {
    slug: 'vienna-airport-to-wiener-neustadt',
    from: 'Flughafen Wien (VIE)',
    to: 'Wiener Neustadt',
    distance: '~45 km',
    driveTime: '~40 Min.',
    routeDescription: 'Südlich über die A4 und die S6, eine kurze Fahrt in Niederösterreichs zweitgrößte Stadt.',
    whyBook: [
      'Schneller, direkter Transfer für Geschäftsreisen südlich von Wien',
      'Kein Regionalzugumstieg mit Gepäck',
      'Festpreis, Tür zu Tür',
    ],
  },
  {
    slug: 'vienna-airport-to-sopron',
    from: 'Flughafen Wien (VIE)',
    to: 'Sopron',
    distance: '~90 km',
    driveTime: '~1 Std.',
    routeDescription: 'Südöstlich über die A4-Autobahn, Grenzübertritt nach Ungarn bei Klingenbach nach Sopron.',
    whyBook: [
      'Ein Fahrzeug für die gesamte grenzüberschreitende Fahrt, inklusive ungarischer Grenze',
      'Beliebt für Wellness- und Weintourismus gleich hinter der Grenze',
      'Festpreis im Voraus vereinbart',
    ],
    crossBorder: true,
  },
  {
    slug: 'vienna-airport-to-prague',
    from: 'Flughafen Wien (VIE)',
    to: 'Prag',
    distance: '~330 km',
    driveTime: '~3 Std. 15 Min.',
    routeDescription: 'Nördlich über die A5 Weinviertel Autobahn nach Tschechien über Mikulov, weiter auf der D52/D1 nach Prag.',
    whyBook: [
      'Direkte Alternative zum Anschlussflug für VIE-Ankünfte mit Ziel Prag',
      'Ein lizenzierter Fahrer für die gesamte grenzüberschreitende Fahrt',
      'Festpreis im Voraus vereinbart',
    ],
    crossBorder: true,
  },
  {
    slug: 'salzburg-airport-to-bad-ischl',
    from: 'Flughafen Salzburg (SZG)',
    to: 'Bad Ischl',
    distance: '~55 km',
    driveTime: '~50 Min.',
    routeDescription: 'Östlich über die Wolfgangsee-Straße (B158) durch Fuschl und St. Gilgen in den Salzkammergut-Kurort Bad Ischl.',
    whyBook: [
      'Direkter Ankunftstransfer für Gäste des Salzkammergut-Seengebiets',
      'Keine regionale Busverbindung ab Salzburg nötig',
      'Festpreis inklusive Flugverfolgung',
    ],
  },
  {
    slug: 'innsbruck-airport-to-garmisch',
    from: 'Flughafen Innsbruck (INN)',
    to: 'Garmisch-Partenkirchen',
    distance: '~65 km',
    driveTime: '~1 Std.',
    routeDescription: 'Nördlich über die B171 und die B2, Grenzübertritt nach Bayern bei Scharnitz nach Garmisch-Partenkirchen.',
    whyBook: [
      'Ein Fahrzeug für die gesamte grenzüberschreitende Fahrt, inklusive deutscher Grenze',
      'Beliebt für Zugspitze-Tagesausflüge und Wintersportgäste',
      'Festpreis im Voraus vereinbart',
    ],
    crossBorder: true,
  },
  {
    slug: 'innsbruck-airport-to-bolzano',
    from: 'Flughafen Innsbruck (INN)',
    to: 'Bozen',
    distance: '~210 km',
    driveTime: '~2 Std. 15 Min.',
    routeDescription: 'Südlich über die A13 Brennerautobahn, Österreichs wichtigste Route nach Italien, über den Brennerpass nach Südtirol.',
    whyBook: [
      'Die Überquerung des Brennerpasses und die italienische Vignette sind im Festpreis inbegriffen',
      'Direkt ab Ankunft, ohne Zugumstieg am Bahnhof Bozen',
      'Komfortabel für eine landschaftliche Ankunft in den Dolomiten',
    ],
    crossBorder: true,
  },
  {
    slug: 'graz-airport-to-maribor',
    from: 'Flughafen Graz (GRZ)',
    to: 'Maribor',
    distance: '~100 km',
    driveTime: '~1 Std. 15 Min.',
    routeDescription: 'Südlich über die A9 Pyhrn Autobahn und die A2 zum Grenzübergang Spielfeld, weiter nach Slowenien nach Maribor.',
    whyBook: [
      'Direkter grenzüberschreitender Ankunftstransfer in Sloweniens Weinregion',
      'Keine separate Buchung eines grenzüberschreitenden Taxis nötig',
      'Festpreis inklusive slowenischer Vignette',
    ],
    crossBorder: true,
  },
  {
    slug: 'graz-airport-to-klagenfurt',
    from: 'Flughafen Graz (GRZ)',
    to: 'Klagenfurt',
    distance: '~140 km',
    driveTime: '~1 Std. 30 Min.',
    routeDescription: 'Westlich über die A2 Südautobahn, eine direkte regionsübergreifende Fahrt in die Kärntner Seenlandschaft.',
    whyBook: [
      'Nützlich, wenn eine Flugverbindung zwischen Österreichs zwei südlichen Flughäfen unpraktisch ist',
      'Direkt zu Hotels in Klagenfurt oder ans Wörthersee-Ufer',
      'Festpreis unabhängig vom Verkehr',
    ],
  },
  {
    slug: 'linz-airport-to-salzburg',
    from: 'Flughafen Linz (LNZ)',
    to: 'Salzburg',
    distance: '~130 km',
    driveTime: '~1 Std. 25 Min.',
    routeDescription: 'Westlich auf der A1 Westautobahn, derselben Straßenverbindung wie zwischen den beiden Städten.',
    whyBook: [
      'Regionsübergreifende Geschäftsreise ohne Zugumstieg am Linzer Hauptbahnhof',
      'Direkt zu Hotels oder in die Altstadt von Salzburg',
      'Festpreis vor Fahrtantritt vereinbart',
    ],
  },
  {
    slug: 'linz-airport-to-vienna',
    from: 'Flughafen Linz (LNZ)',
    to: 'Wien',
    distance: '~185 km',
    driveTime: '~1 Std. 45 Min. – 2 Std.',
    routeDescription: 'Östlich auf der A1 Westautobahn entlang des Donaukorridors nach Wien.',
    whyBook: [
      'Geschäftsreiseverbindung in die Hauptstadt ohne Zugumstieg',
      'Direkt zu Hotels in Wien oder weiter zum Flughafen Wien',
      'Festpreis vor Fahrtantritt vereinbart',
    ],
  },
  {
    slug: 'linz-airport-to-passau',
    from: 'Flughafen Linz (LNZ)',
    to: 'Passau',
    distance: '~85 km',
    driveTime: '~1 Std.',
    routeDescription: 'Nördlich über die A7 Mühlkreisautobahn, Grenzübertritt nach Bayern bei Wegscheid nach Passau.',
    whyBook: [
      'Kurzer grenzüberschreitender Transfer für Donau-Flusskreuzfahrtpassagiere in Passau',
      'Ein Fahrzeug für die gesamte grenzüberschreitende Fahrt',
      'Festpreis im Voraus vereinbart',
    ],
    crossBorder: true,
  },
  {
    slug: 'linz-airport-to-prague',
    from: 'Flughafen Linz (LNZ)',
    to: 'Prag',
    distance: '~215 km',
    driveTime: '~2 Std. 30 Min.',
    routeDescription: 'Nördlich über die A7 Mühlkreisautobahn, Grenzübertritt bei Wullowitz nach Tschechien auf der D3 Richtung Prag.',
    whyBook: [
      'Direkte Hauptstadtverbindung für Ankünfte am Flughafen Linz',
      'Ein lizenzierter Fahrer für die gesamte grenzüberschreitende Fahrt',
      'Festpreis im Voraus vereinbart',
    ],
    crossBorder: true,
  },
  {
    slug: 'klagenfurt-airport-to-ljubljana',
    from: 'Flughafen Klagenfurt (KLU)',
    to: 'Ljubljana',
    distance: '~85 km',
    driveTime: '~1 Std.',
    routeDescription: 'Südlich über die B91 Loiblpass-Straße oder die A11 durch den Karawankentunnel direkt nach Slowenien.',
    whyBook: [
      'Direkte Hauptstadtverbindung für KLU-Ankünfte, inklusive Tunnelmaut',
      'Ein Fahrzeug für die gesamte grenzüberschreitende Fahrt',
      'Festpreis im Voraus vereinbart',
    ],
    crossBorder: true,
  },
  {
    slug: 'klagenfurt-airport-to-bad-kleinkirchheim',
    from: 'Flughafen Klagenfurt (KLU)',
    to: 'Bad Kleinkirchheim',
    distance: '~55 km',
    driveTime: '~55 Min.',
    routeDescription: 'Westlich über die A2 und die B93 durch die Nockberge nach Bad Kleinkirchheim.',
    whyBook: [
      'Direkter Ankunftstransfer zum Spa- und Skiresort, der Heimat von Franz Klammer',
      'Keine regionale Busverbindung ab Klagenfurt oder Villach nötig',
      'Festpreis inklusive Flugverfolgung',
    ],
  },
  {
    slug: 'innsbruck-airport-to-alpbach',
    from: 'Flughafen Innsbruck (INN)',
    to: 'Alpbach',
    distance: '~60 km',
    driveTime: '~1 Std.',
    routeDescription: 'Östlich auf der A12 Inntalautobahn, Ausfahrt auf die B171/L5 ins Alpbachtal.',
    whyBook: [
      'Direkt zu einem der meistfotografierten Alpendörfer Österreichs',
      'Auch beliebt für Konferenz- und Firmenreisen',
      'Festpreis vor Fahrtantritt vereinbart',
    ],
  },
  {
    slug: 'innsbruck-airport-to-obergurgl',
    from: 'Flughafen Innsbruck (INN)',
    to: 'Obergurgl-Hochgurgl',
    distance: '~90 km',
    driveTime: '~1 Std. 30 Min.',
    routeDescription: 'Westlich über die A12 bis zur Ausfahrt Ötztal, dann südlich auf der B186 Ötztaler Straße zum Talschluss.',
    whyBook: [
      'Direkt zur höchstgelegenen Pfarrgemeinde Österreichs, ohne Regionalbus das Ötztal hinauf',
      'Zuverlässige Schneelage bis weit ins Frühjahr',
      'Fester, transparenter Preis inklusive Autobahnmaut',
    ],
  },
  {
    slug: 'salzburg-airport-to-flachau',
    from: 'Flughafen Salzburg (SZG)',
    to: 'Flachau',
    distance: '~80 km',
    driveTime: '~45 Min.',
    routeDescription: 'Südlich über die A10 Tauernautobahn, das nächstgelegene Ski-Amadé-Dorf zum Flughafen Salzburg.',
    whyBook: [
      'Einer der kürzesten Flughafen-zu-Resort-Wege im Ski-Amadé-Netzwerk',
      'Beliebt für Wochenendausflüge ab Salzburg, Wien und München',
      'Festpreis inklusive Flugverfolgung',
    ],
  },
  {
    slug: 'graz-airport-to-schladming',
    from: 'Flughafen Graz (GRZ)',
    to: 'Schladming',
    distance: '~100 km',
    driveTime: '~1 Std. 30 Min.',
    routeDescription: 'Westlich über die A9 Pyhrn Autobahn durchs Gesäuse ins Ennstal nach Schladming.',
    whyBook: [
      'Direkte Route zum steirischen Vorzeige-Skiort ab dem eigenen Landesflughafen',
      'Kein Shuttlebus- oder Regionalzugumstieg mit Skiausrüstung',
      'Festpreis inklusive Autobahnmaut',
    ],
  },
  {
    slug: 'klagenfurt-airport-to-nassfeld',
    from: 'Flughafen Klagenfurt (KLU)',
    to: 'Nassfeld',
    distance: '~65 km',
    driveTime: '~1 Std.',
    routeDescription: 'Westlich über die A2 und die B111 Gailtal Straße ins Gailtal nach Nassfeld.',
    whyBook: [
      'Direkt zu Österreichs sonnigstem, südexponiertem Skigebiet',
      'Praktisch für Gäste, die Skifahren mit einem Abstecher über die nahe italienische Grenze verbinden',
      'Festpreis inklusive Flugverfolgung',
    ],
  },
  {
    slug: 'klagenfurt-airport-to-turracher-hoehe',
    from: 'Flughafen Klagenfurt (KLU)',
    to: 'Turracher Höhe',
    distance: '~75 km',
    driveTime: '~1 Std. 15 Min.',
    routeDescription: 'Nordwestlich über die B93 und die B95 hinauf zum Passort Turracher Höhe.',
    whyBook: [
      'Direkt zum Zwei-Seen-Passresort an der Grenze zwischen Kärnten und der Steiermark',
      'Winterfeste Fahrzeuge für die Bergpassanfahrt',
      'Fester, transparenter Preis vor Fahrtantritt vereinbart',
    ],
  },
  {
    slug: 'vienna-to-eisenstadt',
    from: 'Wien',
    to: 'Eisenstadt',
    distance: '~60 km',
    driveTime: '~50 Min.',
    routeDescription: 'Südlich über die A2 und die A3 Süd Ost Autobahn ins Burgenländer Weinland und in die Landeshauptstadt.',
    whyBook: [
      'Direkter Stadt-zu-Stadt-Transfer für Weintourismus oder Geschäftsreisen',
      'Keine regionale Busverbindung nötig',
      'Festpreis, Tür zu Tür',
    ],
  },
  {
    slug: 'graz-to-klagenfurt',
    from: 'Graz',
    to: 'Klagenfurt',
    distance: '~140 km',
    driveTime: '~1 Std. 30 Min.',
    routeDescription: 'Westlich über die A2 Südautobahn zwischen Österreichs zweit- und sechstgrößter Stadt.',
    whyBook: [
      'Regionsübergreifende Geschäfts- und Freizeitreisen ohne Regionalzugumstieg',
      'Direkt zu Hotels in Klagenfurt oder ans Wörthersee-Ufer',
      'Festpreis unabhängig vom Verkehr',
    ],
  },
  {
    slug: 'graz-to-schladming',
    from: 'Graz',
    to: 'Schladming',
    distance: '~100 km',
    driveTime: '~1 Std. 30 Min.',
    routeDescription: 'Westlich über die A9 Pyhrn Autobahn durchs Gesäuse ins Ennstal.',
    whyBook: [
      'Beliebte Wochenendroute in der Skisaison ab der steirischen Landeshauptstadt',
      'Kein Bahnhofsumstieg mit Skiausrüstung',
      'Festpreis inklusive Autobahnmaut',
    ],
  },
  {
    slug: 'salzburg-to-bad-gastein',
    from: 'Salzburg',
    to: 'Bad Gastein',
    distance: '~95 km',
    driveTime: '~1 Std. 15 Min.',
    routeDescription: 'Südlich über die A10 Tauernautobahn und die B167 das Gasteinertal hinauf, derselbe Korridor wie ab dem Flughafen Salzburg.',
    whyBook: [
      'Direkter Stadt-zu-Resort-Transfer zum historischen Kurort',
      'Komfortabel für Wintersport ebenso wie für Wellnessreisen im Sommer',
      'Festpreis vor Fahrtantritt vereinbart',
    ],
  },
  {
    slug: 'salzburg-to-st-wolfgang',
    from: 'Salzburg',
    to: 'St. Wolfgang',
    distance: '~50 km',
    driveTime: '~50 Min.',
    routeDescription: 'Östlich über die Wolfgangsee-Straße (B158) durch Fuschl in das Seedorf St. Wolfgang.',
    whyBook: [
      'Beliebte Salzkammergut-Tagesausflugs- und Transferroute',
      'Direkt zu Hotels am Seeufer, kein regionaler Busfahrplan',
      'Flexible Abfahrtszeiten',
    ],
  },
  {
    slug: 'klagenfurt-to-velden',
    from: 'Klagenfurt',
    to: 'Velden am Wörthersee',
    distance: '~20 km',
    driveTime: '~20 Min.',
    routeDescription: 'Westlich über die B83, eine kurze Fahrt am Wörthersee-Ufer entlang nach Velden.',
    whyBook: [
      'Kurzer, häufig gebuchter Transfer zu einem der bekanntesten Seeresorts Österreichs',
      'Direkt zu Hotels am Seeufer und ins Casinoviertel',
      'Festpreis, Tür zu Tür',
    ],
  },
  {
    slug: 'villach-to-lienz',
    from: 'Villach',
    to: 'Lienz',
    distance: '~100 km',
    driveTime: '~1 Std. 15 Min.',
    routeDescription: 'Westlich über die B100 Drautal Straße, eine landschaftlich reizvolle Talroute durch Osttirol nach Lienz.',
    whyBook: [
      'Direkter regionsübergreifender Transfer zwischen Kärnten und Osttirol',
      'Komfortabel für die landschaftliche Fahrt durchs Drautal',
      'Festpreis vor Fahrtantritt vereinbart',
    ],
  },
  {
    slug: 'wels-to-salzburg',
    from: 'Wels',
    to: 'Salzburg',
    distance: '~100 km',
    driveTime: '~1 Std.',
    routeDescription: 'Westlich auf der A1 Westautobahn, derselbe Korridor wie von Linz nach Salzburg.',
    whyBook: [
      'Direkter Geschäftstransfer ohne Zugverbindung über Linz',
      'Festpreis unabhängig vom Verkehr',
      'Komfortabel für Messe- und Konferenzreisen',
    ],
  },
  {
    slug: 'wels-to-linz',
    from: 'Wels',
    to: 'Linz',
    distance: '~30 km',
    driveTime: '~25 Min.',
    routeDescription: 'Östlich auf der A25 Welser Autobahn, eine kurze direkte Fahrt zwischen den beiden oberösterreichischen Städten.',
    whyBook: [
      'Kurzer, häufig gebuchter Geschäfts- und Messetransfer',
      'Kein Regionalzugumstieg nötig',
      'Festpreis, Tür zu Tür',
    ],
  },
  {
    slug: 'graz-to-maribor',
    from: 'Graz',
    to: 'Maribor',
    distance: '~100 km',
    driveTime: '~1 Std. 15 Min.',
    routeDescription: 'Südlich über die A9 Pyhrn Autobahn und die A2 zum Grenzübergang Spielfeld, weiter nach Slowenien nach Maribor.',
    whyBook: [
      'Kurze grenzüberschreitende Geschäftsfahrt in Sloweniens zweitgrößte Stadt',
      'Ein Fahrzeug für die gesamte Fahrt, inklusive Grenzübertritt',
      'Festpreis inklusive slowenischer Vignette',
    ],
    crossBorder: true,
  },
  {
    slug: 'linz-to-ceske-budejovice',
    from: 'Linz',
    to: 'České Budějovice',
    distance: '~145 km',
    driveTime: '~1 Std. 45 Min.',
    routeDescription: 'Nördlich über die A7 Mühlkreisautobahn, Grenzübertritt bei Wullowitz nach Tschechien auf der D3.',
    whyBook: [
      'Regionale grenzüberschreitende Geschäftsverbindung nach Südböhmen',
      'Ein lizenzierter Fahrer für die gesamte Fahrt',
      'Festpreis im Voraus vereinbart',
    ],
    crossBorder: true,
  },
  {
    slug: 'bregenz-to-st-gallen',
    from: 'Bregenz',
    to: 'St. Gallen',
    distance: '~55 km',
    driveTime: '~50 Min.',
    routeDescription: 'Westlich über die Schweizer Grenze bei Rheineck, eine kurze Fahrt nach St. Gallen.',
    whyBook: [
      'Kurze grenzüberschreitende Geschäftsfahrt in die Ostschweiz',
      'Schweizer Vignette im Festpreis inbegriffen',
      'Keine separate Buchung eines grenzüberschreitenden Taxis nötig',
    ],
    crossBorder: true,
  },
  {
    slug: 'bregenz-to-vaduz',
    from: 'Bregenz',
    to: 'Vaduz',
    distance: '~60 km',
    driveTime: '~50 Min.',
    routeDescription: 'Südlich durchs Rheintal, Grenzübertritt nach Liechtenstein bei Feldkirch nach Vaduz.',
    whyBook: [
      'Direkter grenzüberschreitender Transfer für Liechtensteins Finanzsektor',
      'Ein Fahrzeug für die gesamte Fahrt, inklusive zweier Grenzübertritte',
      'Festpreis im Voraus vereinbart',
    ],
    crossBorder: true,
  },
  {
    slug: 'eisenstadt-to-sopron',
    from: 'Eisenstadt',
    to: 'Sopron',
    distance: '~25 km',
    driveTime: '~25 Min.',
    routeDescription: 'Ein kurzer grenzüberschreitender Sprung über die B84, Grenzübertritt nach Ungarn bei Klingenbach nach Sopron.',
    whyBook: [
      'Sehr kurze grenzüberschreitende Fahrt zwischen zwei Weinregion-Hauptstädten',
      'Keine separate Buchung eines grenzüberschreitenden Taxis nötig',
      'Festpreis inklusive Grenzübertritt',
    ],
    crossBorder: true,
  },
  {
    slug: 'wiener-neustadt-to-sopron',
    from: 'Wiener Neustadt',
    to: 'Sopron',
    distance: '~45 km',
    driveTime: '~40 Min.',
    routeDescription: 'Südöstlich über die S4 und die B61, Grenzübertritt nach Ungarn bei Deutschkreutz nach Sopron.',
    whyBook: [
      'Kurze grenzüberschreitende Geschäfts- oder Wellnessfahrt',
      'Ein Fahrzeug für die gesamte Fahrt, inklusive Grenzübertritt',
      'Festpreis im Voraus vereinbart',
    ],
    crossBorder: true,
  },
  {
    slug: 'feldkirch-to-vaduz',
    from: 'Feldkirch',
    to: 'Vaduz',
    distance: '~20 km',
    driveTime: '~20 Min.',
    routeDescription: 'Eine sehr kurze grenzüberschreitende Fahrt durchs Rheintal in Liechtensteins Hauptstadt.',
    whyBook: [
      'Die kürzeste grenzüberschreitende Route im Netzwerk',
      'Beliebt für Liechtensteiner Geschäfts- und Bankreisen',
      'Festpreis inklusive Grenzübertritt',
    ],
    crossBorder: true,
  },
  {
    slug: 'dornbirn-to-zurich',
    from: 'Dornbirn',
    to: 'Zürich',
    distance: '~110 km',
    driveTime: '~1 Std. 15 Min.',
    routeDescription: 'Westlich über die Schweizer Grenze bei St. Margrethen auf die Schweizer Autobahn A1 nach Zürich.',
    whyBook: [
      'Grenzüberschreitende Geschäftsroute für Vorarlbergs größte Stadt',
      'Schweizer Vignette im Festpreis inbegriffen',
      'Ein Fahrzeug für die gesamte Fahrt',
    ],
    crossBorder: true,
  },
  {
    slug: 'kufstein-to-munich',
    from: 'Kufstein',
    to: 'München',
    distance: '~100 km',
    driveTime: '~1 Std. 15 Min.',
    routeDescription: 'Nördlich über den deutschen A93/A8-Korridor, eine kurze grenzüberschreitende Fahrt von der Tiroler Grenzstadt nach München.',
    whyBook: [
      'Kurze grenzüberschreitende Geschäfts- oder Freizeitroute nach Bayern',
      'Ein Fahrzeug für die gesamte Fahrt, inklusive deutscher Grenze',
      'Festpreis im Voraus vereinbart',
    ],
    crossBorder: true,
  },
  {
    slug: 'villach-to-bad-kleinkirchheim',
    from: 'Villach',
    to: 'Bad Kleinkirchheim',
    distance: '~35 km',
    driveTime: '~40 Min.',
    routeDescription: 'Nördlich über die B93 durch die Nockberge nach Bad Kleinkirchheim.',
    whyBook: [
      'Kurzer Resort-Transfer zum Spa- und Skiort, der Heimat von Franz Klammer',
      'Direkt zu Ski-in/Ski-out-Hotels',
      'Festpreis, Tür zu Tür',
    ],
  },
  {
    slug: 'zell-am-see-to-bad-gastein',
    from: 'Zell am See',
    to: 'Bad Gastein',
    distance: '~35 km',
    driveTime: '~40 Min.',
    routeDescription: 'Südlich über die B311 und die B167 durchs Gasteinertal nach Bad Gastein.',
    whyBook: [
      'Kurzer Resort-zu-Resort-Transfer für Gäste, die einen Aufenthalt auf zwei Salzburger Täler aufteilen',
      'Keine regionale Busverbindung nötig',
      'Festpreis, Tür zu Tür',
    ],
  },
]
