export type RoutePair = {
  slug: string
  from: string
  to: string
  distance: string
  driveTime: string
  routeDescription: string
  whyBook: string[]
  crossBorder?: boolean
  seoTitle?: string
  seoDescription?: string
}

export const routes: RoutePair[] = [
  {
    slug: 'vienna-airport-to-salzburg',
    from: 'Flughafen Wien (VIE)',
    to: 'Salzburg',
    distance: '~300 km',
    driveTime: '~2 Std. 45 Min. – 3 Std.',
    routeDescription:
      'Die Route führt auf der A1 Westautobahn, Österreichs wichtigster Ost-West-Achse, an Linz vorbei weiter nach Salzburg.',
    whyBook: [
      'Kein Umsteigen auf Zug oder Anschlussflug für eine Ankunft am selben Tag',
      'Ein Festpreis unabhängig von Verkehr oder verspäteter Landung',
      'Direkt zu Ihrem Hotel in Salzburg oder in die Altstadt, kein Bahnhofstransfer',
    ],
  },
  {
    slug: 'vienna-airport-to-graz',
    from: 'Flughafen Wien (VIE)',
    to: 'Graz',
    distance: '~200 km',
    driveTime: '~2 Std. 15 Min.',
    routeDescription:
      'Die Route folgt der A2 Südautobahn durch Niederösterreich und die Steiermark direkt nach Graz.',
    whyBook: [
      'Eine der direkteren Flughafen-zu-Stadt-Strecken in Österreich',
      'Nützlich, wenn der Flughafen Graz (GRZ) keine passende Verbindung von Ihrem Startort bietet',
      'Festpreis inklusive Flugverfolgung',
    ],
  },
  {
    slug: 'vienna-to-salzburg',
    from: 'Wien',
    to: 'Salzburg',
    distance: '~295 km',
    driveTime: '~2 Std. 45 Min.',
    routeDescription:
      'Eine direkte Fahrt auf der A1 Westautobahn — dieselbe Route wie zum Flughafen, jedoch ab dem Wiener Stadtzentrum.',
    whyBook: [
      'Schneller von Tür zu Tür als der Zug, sobald man Anfahrt und Abholung an den Bahnhöfen mitrechnet',
      'Platz für Gepäck, das nicht ins Zugabteil passt',
      'Abfahrt zur passenden Zeit, kein fester Fahrplan',
    ],
  },
  {
    slug: 'vienna-to-graz',
    from: 'Wien',
    to: 'Graz',
    distance: '~195 km',
    driveTime: '~2 Std.',
    routeDescription: 'Südwärts auf der A2 Südautobahn, eine der landschaftlich schönsten Autobahnstrecken Österreichs, die durch Niederösterreich in die Steiermark führt.',
    whyBook: [
      'Direkt vom Stadtzentrum zum Stadtzentrum in rund zwei Stunden',
      'Eine übliche Strecke für Geschäftsreisen zwischen Österreichs zwei größten Städten',
      'Kein Umstieg auf Regionalverkehr an beiden Enden nötig',
    ],
  },
  {
    slug: 'salzburg-to-innsbruck',
    from: 'Salzburg',
    to: 'Innsbruck',
    distance: '~140–200 km',
    driveTime: '~1 Std. 30 Min. – 2 Std. 15 Min.',
    routeDescription:
      'Die schnellste Route führt kurz über die deutsche A8 durch Bayern, bevor sie bei Kufstein wieder auf die österreichische A12 wechselt. Eine rein österreichische Alternative verläuft über die B178/A12 durch Kitzbühel und Wörgl, etwas länger, aber ohne Grenzübertritt.',
    whyBook: [
      'Wir übernehmen den deutsch-österreichischen Grenzübertritt als Teil des Festpreises — keine separate Buchung nötig',
      'Ein Fahrzeug die ganze Strecke, je nachdem welche Route an dem Tag schneller ist',
      'Beliebt, um zwei der meistbesuchten Städte Österreichs ohne Flug zu verbinden',
    ],
    crossBorder: true,
  },
  {
    slug: 'linz-to-vienna',
    from: 'Linz',
    to: 'Wien',
    distance: '~185 km',
    driveTime: '~1 Std. 45 Min. – 2 Std.',
    routeDescription: 'Ostwärts auf der A1 Westautobahn, derselben Achse wie zwischen Wien und Salzburg, streckenweise entlang des Donautals.',
    whyBook: [
      'Eine übliche Strecke für Geschäftsreisen zwischen Oberösterreich und der Hauptstadt',
      'Direkt zum Flughafen Wien als Zusatzstopp bei einem Weiterflug',
      'Festpreis vor Fahrtantritt vereinbart',
    ],
  },
  {
    slug: 'vienna-to-bratislava',
    from: 'Wien',
    to: 'Bratislava',
    distance: '~80 km',
    driveTime: '~1 Std.',
    routeDescription:
      'Eine der kürzesten grenzüberschreitenden Hauptstadt-zu-Hauptstadt-Fahrten Europas, über die A6-Autobahn durch Kittsee bis zur slowakischen Grenze.',
    whyBook: [
      'Schnell genug für eine Rückfahrt am selben Tag',
      'Kein Fahrzeugwechsel oder Papierkram an der Grenze — das übernehmen wir',
      'Beliebt für Geschäftstermine, Tagesausflüge und Anschlüsse an den Flughafen Wien',
    ],
    crossBorder: true,
    seoTitle: 'Wien nach Bratislava Privattransfer | 1 Stunde, Festpreis',
    seoDescription:
      'Privater Chauffeurtransfer vom Wiener Stadtzentrum nach Bratislava — 80 km, etwa eine Stunde, Festpreis, kein Grenzstopp. Ideal für Geschäftstermine, Tagesausflüge und Fahrten von Hotel zu Hotel.',
  },
  {
    slug: 'vienna-to-budapest',
    from: 'Wien',
    to: 'Budapest',
    distance: '~245 km',
    driveTime: '~2 Std. 30 Min. – 3 Std.',
    routeDescription:
      'Südöstlich über die A4-Autobahn zur ungarischen Grenze bei Hegyeshalom, weiter auf der M15/M1 nach Budapest.',
    whyBook: [
      'Direkte Alternative zu Anschlussflug oder Zugumstieg',
      'Ein lizenzierter Fahrer die gesamte Strecke, inklusive Grenzübertritt',
      'Komfortabel für Geschäftsreisen oder Wochenendtrips zwischen den beiden Hauptstädten',
    ],
    crossBorder: true,
  },
  {
    slug: 'salzburg-to-munich',
    from: 'Salzburg',
    to: 'München',
    distance: '~145 km',
    driveTime: '~1 Std. 30 Min.',
    routeDescription: 'Eine kurze grenzüberschreitende Fahrt nordwärts auf der deutschen A8 — eine der meistgebuchten internationalen Strecken ab Salzburg.',
    whyBook: [
      'Beliebt für Anschlüsse zum Flughafen München (MUC) für Weiterflüge',
      'Keine separate Buchung eines grenzüberschreitenden Taxis nötig',
      'Festpreis im Voraus vereinbart, unabhängig vom Grenzverkehr',
    ],
    crossBorder: true,
  },
  {
    slug: 'innsbruck-airport-to-kitzbuehel',
    from: 'Flughafen Innsbruck (INN)',
    to: 'Kitzbühel',
    distance: '~90 km',
    driveTime: '~1 Std.',
    routeDescription: 'Ostwärts auf der A12 Inntalautobahn, dann über die B170/B161 nach Kitzbühel — die direkteste Flughafen-zu-Resort-Strecke der Region.',
    whyBook: [
      'Winterfeste Fahrzeuge mit Platz für Ski und Snowboards',
      'Direkt zu Ihrem Chalet oder Hotel, kein Shuttlebus-Transfer',
      'Die kürzeste Flughafen-zu-Resort-Fahrzeit unter den großen Tiroler Skiorten',
    ],
  },
  {
    slug: 'innsbruck-airport-to-st-anton',
    from: 'Flughafen Innsbruck (INN)',
    to: 'St. Anton am Arlberg',
    distance: '~100 km',
    driveTime: '~1 Std. 10 Min.',
    routeDescription: 'Westlich auf der A12 Inntalautobahn und der S16 Arlberg Schnellstraße direkt nach St. Anton.',
    whyBook: [
      'Direkter Transfer mit Allradfahrzeug zu Ihrem Arlberg-Chalet',
      'Geräumige Vans für Skiausrüstung und großes Gepäck',
      'Flugverfolgung und Fahrerempfang direkt in der Ankunftshalle des Flughafens Innsbruck',
    ],
  },
  {
    slug: 'innsbruck-airport-to-ischgl',
    from: 'Flughafen Innsbruck (INN)',
    to: 'Ischgl',
    distance: '~100 km',
    driveTime: '~1 Std. 15 Min.',
    routeDescription: 'Westlich über die A12 Inntalautobahn und die B188 Silvrettastraße das Paznauntal hinauf nach Ischgl.',
    whyBook: [
      'Ruhiger Transfer durchs Paznauntal mit erfahrenen Alpenfahrern',
      'Fester, transparenter Preis ohne versteckte Bergmautzuschläge',
      'Komfortable Fahrzeuge, ausgestattet für winterliche Schneeverhältnisse',
    ],
  },
  {
    slug: 'innsbruck-airport-to-soelden',
    from: 'Flughafen Innsbruck (INN)',
    to: 'Sölden',
    distance: '~85 km',
    driveTime: '~1 Std. 10 Min.',
    routeDescription: 'Westlich auf der A12 bis zur Ausfahrt Ötztal, dann südlich auf der B186 Ötztaler Straße nach Sölden.',
    whyBook: [
      'Schnellster privater Transfer vom Flughafen Innsbruck ins Gletschergebiet Ötztal',
      'Direkt zu den Hotels in Sölden und zur „007 Elements“-Basis',
      'Alles inklusive zum Festpreis, mit Überwachung von Flugverspätungen',
    ],
  },
  {
    slug: 'innsbruck-airport-to-mayrhofen',
    from: 'Flughafen Innsbruck (INN)',
    to: 'Mayrhofen',
    distance: '~75 km',
    driveTime: '~1 Std.',
    routeDescription: 'Östlich auf der A12 Inntalautobahn, Ausfahrt Zillertal auf die B169 direkt nach Mayrhofen.',
    whyBook: [
      'Direkter Transfer ins Zillertal, ganz ohne Zugumstieg',
      'Winterfeste Fahrzeuge für Besucher des Hintertuxer Gletschers',
      'Persönliche Abholung direkt vor der Ankunftshalle in Innsbruck',
    ],
  },
  {
    slug: 'innsbruck-airport-to-lech',
    from: 'Flughafen Innsbruck (INN)',
    to: 'Lech am Arlberg',
    distance: '~120 km',
    driveTime: '~1 Std. 30 Min.',
    routeDescription: 'Westlich über die A12 und die S16 durch den Arlbergpass oder den Flexenpass-Tunnel nach Lech.',
    whyBook: [
      'Exklusiver VIP-Transfer zu luxuriösen 5-Sterne-Hotels am Arlberg',
      'Professionelle Chauffeure mit Erfahrung im winterlichen Passverkehr',
      'Geräumige V-Klasse- und S-Klasse-Fahrzeuge verfügbar',
    ],
  },
  {
    slug: 'salzburg-airport-to-kitzbuehel',
    from: 'Flughafen Salzburg (SZG)',
    to: 'Kitzbühel',
    distance: '~75 km',
    driveTime: '~1 Std. 15 Min.',
    routeDescription: 'Südwestlich über die Loferer Straße (B178) durch Unken und Waidring nach Kitzbühel.',
    whyBook: [
      'Beliebte Skiroute für Charterflüge am Flughafen Salzburg',
      'Komfortabler Tür-zu-Tür-Service direkt zu den Chalets in Kitzbühel',
      'Kein mühsames Schleppen schwerer Skitaschen im Regionalverkehr',
    ],
  },
  {
    slug: 'salzburg-airport-to-zell-am-see',
    from: 'Flughafen Salzburg (SZG)',
    to: 'Zell am See',
    distance: '~80 km',
    driveTime: '~1 Std. 15 Min.',
    routeDescription: 'Südlich über die A10 Tauernautobahn oder die B311 Pinzgauer Straße nach Zell am See.',
    whyBook: [
      'Direkter Transfer ans Seeufer und zum Gletscherresort Kaprun',
      'Festpreis inklusive Gepäck, Skiausrüstung und Mautgebühren',
      'Rund um die Uhr verfügbar, auch für frühe Charterflug-Ankünfte',
    ],
  },
  {
    slug: 'salzburg-airport-to-saalbach',
    from: 'Flughafen Salzburg (SZG)',
    to: 'Saalbach-Hinterglemm',
    distance: '~85 km',
    driveTime: '~1 Std. 20 Min.',
    routeDescription: 'Südwestlich über die B178 und die B311 ins Glemmtal Richtung Saalbach.',
    whyBook: [
      'Unkomplizierte Anreise ins Skicircus-Skigebiet',
      'Geräumige Kleinbusse und Mercedes V-Klasse für Gruppen und Familien',
      'Direkte Ablieferung vor Ihrer Hoteltür',
    ],
  },
  {
    slug: 'salzburg-airport-to-bad-gastein',
    from: 'Flughafen Salzburg (SZG)',
    to: 'Bad Gastein',
    distance: '~95 km',
    driveTime: '~1 Std. 15 Min.',
    routeDescription: 'Südlich über die A10 Tauernautobahn und die B167 das Gasteinertal hinauf nach Bad Gastein.',
    whyBook: [
      'Landschaftlich reizvolle Fahrt direkt zu den historischen Belle-Époque-Spahotels',
      'Komfortabel für Wintersportler und Wellnessgäste im Sommer gleichermaßen',
      'Fester, transparenter Preis inklusive Überwachung von Flugverspätungen',
    ],
  },
  {
    slug: 'munich-airport-to-innsbruck',
    from: 'Flughafen München (MUC)',
    to: 'Innsbruck',
    distance: '~160 km',
    driveTime: '~2 Std.',
    routeDescription: 'Südlich über die deutschen Autobahnen A9 und A8, Grenzübertritt nach Österreich über die A93/A12 Inntalautobahn nach Innsbruck.',
    whyBook: [
      'Nahtloser grenzüberschreitender Transfer vom größten Langstrecken-Drehkreuz Deutschlands',
      'Kein Umstieg mit schwerem Gepäck am Münchner Hauptbahnhof',
      'Lizenzierte grenzüberschreitende Chauffeure zum Festpreis',
    ],
    crossBorder: true,
  },
  {
    slug: 'munich-airport-to-salzburg',
    from: 'Flughafen München (MUC)',
    to: 'Salzburg',
    distance: '~170 km',
    driveTime: '~1 Std. 45 Min.',
    routeDescription: 'Östlich über die deutschen Autobahnen A92 und A8, Grenzübertritt bei Walserberg direkt nach Salzburg.',
    whyBook: [
      'Direkte Verbindung zwischen Langstreckenflügen ab München und der Salzburger Altstadt',
      'Keine Verspätungen der Deutschen Bahn oder Rückgabegebühren für Mietwagen',
      'Professioneller Empfangsservice in Terminal 1 oder 2 des Flughafens München',
    ],
    crossBorder: true,
  },
  {
    slug: 'munich-airport-to-kitzbuehel',
    from: 'Flughafen München (MUC)',
    to: 'Kitzbühel',
    distance: '~165 km',
    driveTime: '~2 Std.',
    routeDescription: 'Südlich über die A8 Richtung Inntaldreieck, weiter über die A93/B173 durch Kufstein nach Kitzbühel.',
    whyBook: [
      'Erste Wahl für internationale Langstreckenreisende nach Kitzbühel',
      'Allradfahrzeuge für winterliche Schneeverhältnisse zwischen Bayern und Tirol',
      'Ein Fahrzeug und ein Fahrer Tür zu Tür, ohne Verzögerungen an der Grenze',
    ],
    crossBorder: true,
  },
  {
    slug: 'munich-airport-to-st-anton',
    from: 'Flughafen München (MUC)',
    to: 'St. Anton am Arlberg',
    distance: '~240 km',
    driveTime: '~2 Std. 45 Min.',
    routeDescription: 'Südlich über die A95 oder A8/A12 durch das Inntal zum Arlberg.',
    whyBook: [
      'Direkter Executive-Transfer für internationale Gäste ab München',
      'Geräumige V-Klasse- und SUV-Flotte für Skigepäck',
      'Alle Grenzvignetten und Mautgebühren im Festpreis inbegriffen',
    ],
    crossBorder: true,
  },
  {
    slug: 'zurich-airport-to-lech',
    from: 'Flughafen Zürich (ZRH)',
    to: 'Lech am Arlberg',
    distance: '~195 km',
    driveTime: '~2 Std. 15 Min.',
    routeDescription: 'Östlich über die Schweizer Autobahnen A1/A3, vorbei am Walensee, Grenzübertritt bei Feldkirch nach Lech.',
    whyBook: [
      'Die führende Luxustransferroute von Zürich zu den 5-Sterne-Resorts am Arlberg',
      'Lizenziert für schweizerisch-österreichische internationale Chauffeurtransfers',
      'Diskreter Executive-Service für anspruchsvolle Reisende',
    ],
    crossBorder: true,
  },
  {
    slug: 'zurich-airport-to-st-anton',
    from: 'Flughafen Zürich (ZRH)',
    to: 'St. Anton am Arlberg',
    distance: '~200 km',
    driveTime: '~2 Std. 15 Min.',
    routeDescription: 'Östlich durch die Schweiz über die A3/A13, Einreise nach Vorarlberg/Tirol über den Arlbergpass oder -tunnel.',
    whyBook: [
      'Bevorzugte Route für internationale Ankünfte über Zürich-Kloten',
      'Geräumige Mercedes-Vans für Familien und Skiausrüstung',
      'Fester grenzüberschreitender Preis ohne versteckte Kosten',
    ],
    crossBorder: true,
  },
  {
    slug: 'vienna-airport-to-bratislava',
    from: 'Flughafen Wien (VIE)',
    to: 'Bratislava',
    distance: '~65 km',
    driveTime: '~45 Min.',
    routeDescription: 'Östlich über die Autobahnen A4 und A6 durch Kittsee über die Grenze nach Bratislava — in beide Richtungen buchbar, Ankunft oder Abfahrt.',
    whyBook: [
      'Kürzester Hauptstadt-zu-Hauptstadt-Transfer Mitteleuropas',
      'Deckt beide Richtungen ab — Ankünfte am Flughafen Wien mit Ziel Slowakei und Abfahrten aus Bratislava zu einem Flug ab Wien',
      'Schnell, direkt und zum Festpreis, Tür zu Tür',
    ],
    crossBorder: true,
    seoTitle: 'Flughafen Wien nach Bratislava Transfer | 45 Minuten, Festpreis',
    seoDescription:
      'Privater Transfer zwischen Flughafen Wien und Bratislava — 65 km, ca. 45 Minuten, Festpreis Tür zu Tür. Deckt sowohl Ankünfte am Flughafen Wien als auch Abfahrten aus Bratislava ab.',
  },
  {
    slug: 'vienna-airport-to-budapest',
    from: 'Flughafen Wien (VIE)',
    to: 'Budapest',
    distance: '~230 km',
    driveTime: '~2 Std. 15 Min.',
    routeDescription: 'Südöstlich über die A4-Autobahn und die ungarische Autobahn M1 direkt nach Budapest.',
    whyBook: [
      'Stark nachgefragter Langstreckentransfer vom Flughafen direkt in die Hauptstadt',
      'Kein Umsteigen am Flughafen oder Bahnhofstransfer nötig',
      'Professioneller, zweisprachiger Fahrer mit Erfahrung auf internationalen Strecken',
    ],
    crossBorder: true,
  },
  {
    slug: 'vienna-airport-to-hallstatt',
    from: 'Flughafen Wien (VIE)',
    to: 'Hallstatt',
    distance: '~300 km',
    driveTime: '~3 Std. 15 Min.',
    routeDescription: 'Westlich auf der A1 Westautobahn bis zur Ausfahrt Regau, weiter über Gmunden und Bad Ischl nach Hallstatt.',
    whyBook: [
      'Direkter Transfer vom Flughafen Wien zum UNESCO-Welterbeort Hallstatt',
      'Kein umständliches Umsteigen zwischen Zug und Fähre mit Gepäck',
      'Optionale landschaftliche Zwischenstopps im Salzkammergut',
    ],
  },
  {
    slug: 'salzburg-to-hallstatt',
    from: 'Salzburg',
    to: 'Hallstatt',
    distance: '~75 km',
    driveTime: '~1 Std. 15 Min.',
    routeDescription: 'Östlich über die Wolfgangsee-Straße (B158) durch Fuschl und St. Gilgen, dann auf der B145 nach Hallstatt.',
    whyBook: [
      'Die beliebteste Tagesausflugs- und Privattransferroute ab Salzburg',
      'Landschaftlich beeindruckende Fahrt vorbei am Fuschlsee und Wolfgangsee',
      'Flexible Abfahrtszeiten, abgestimmt auf Ihren Reiseplan',
    ],
  },
  {
    slug: 'salzburg-airport-to-schladming',
    from: 'Flughafen Salzburg (SZG)',
    to: 'Schladming',
    distance: '~90 km',
    driveTime: '~1 Std.',
    routeDescription: 'Südlich über die A10 Tauernautobahn und die B320 Ennstal Straße direkt nach Schladming.',
    whyBook: [
      'Schnellste Anbindung an die Planai und das Ski-Amadé-4-Berge-Skigebiet',
      'Festpreis inklusive Tauernautobahn-Mautgebühren',
      'Direkte Ablieferung am Hotel, ohne Skiausrüstung im Zug zu transportieren',
    ],
  },
  {
    slug: 'salzburg-airport-to-obertauern',
    from: 'Flughafen Salzburg (SZG)',
    to: 'Obertauern',
    distance: '~90 km',
    driveTime: '~1 Std. 10 Min.',
    routeDescription: 'Südlich über die A10 Tauernautobahn bis zur Ausfahrt Radstadt, dann auf der B99 Radstädter Tauernstraße nach Obertauern.',
    whyBook: [
      'Direkter Transfer zum schneesicheren Passresort in Höhenlage',
      'Allradfahrzeuge mit Erfahrung im winterlichen Bergverkehr',
      'Alles inklusive zum Festpreis, mit Überwachung von Flugverspätungen',
    ],
  },
  {
    slug: 'munich-airport-to-saalbach',
    from: 'Flughafen München (MUC)',
    to: 'Saalbach-Hinterglemm',
    distance: '~215 km',
    driveTime: '~2 Std. 30 Min.',
    routeDescription: 'Südlich über die deutsche A8, Grenzübertritt bei Siegsdorf/Lofer (B178) ins Glemmtal.',
    whyBook: [
      'Beliebter internationaler Langstreckentransfer für Skifahrer aus Großbritannien und Skandinavien',
      'Große Mercedes-V-Klasse-Vans für Gruppen mit viel Skigepäck',
      'Keine Grenzformalitäten oder Sorgen um die Autobahnvignette',
    ],
    crossBorder: true,
  },
  {
    slug: 'munich-airport-to-zell-am-see',
    from: 'Flughafen München (MUC)',
    to: 'Zell am See',
    distance: '~200 km',
    driveTime: '~2 Std. 15 Min.',
    routeDescription: 'Südlich über die A8 und die B311 Pinzgauer Straße direkt zum Zeller See.',
    whyBook: [
      'Direkter Transfer für Langstreckenankünfte in München mit Ziel Zell am See und Gletscher Kaprun',
      'Fester, transparenter Preis, im Voraus vereinbart',
      'Vollständige Flugverfolgung und Empfang in der Ankunftshalle',
    ],
    crossBorder: true,
  },
  {
    slug: 'munich-airport-to-mayrhofen',
    from: 'Flughafen München (MUC)',
    to: 'Mayrhofen',
    distance: '~190 km',
    driveTime: '~2 Std. 15 Min.',
    routeDescription: 'Südlich über die A8 und den A93/A12-Inntalkorridor, Ausfahrt Zillertal (B169) nach Mayrhofen.',
    whyBook: [
      'Direkter Chauffeurtransfer ab München ins Zillertal',
      'Geräumige Fahrzeuge für Gletscher-Skiausrüstung',
      'Komfortable Tür-zu-Tür-Fahrt ohne überfüllte Münchner Züge',
    ],
    crossBorder: true,
  },
  {
    slug: 'munich-airport-to-soelden',
    from: 'Flughafen München (MUC)',
    to: 'Sölden',
    distance: '~240 km',
    driveTime: '~2 Std. 45 Min.',
    routeDescription: 'Südlich über das deutsche Autobahnnetz und die A12/B186 ins Ötztal.',
    whyBook: [
      'Zuverlässiger grenzüberschreitender Transfer für internationale Langstreckengäste',
      'Alle Mautgebühren und Vignetten im Festpreis inbegriffen',
      'Allrad-Mercedes-Fahrzeuge, geeignet für winterliche Alpenstraßen',
    ],
    crossBorder: true,
  },
  {
    slug: 'zurich-airport-to-ischgl',
    from: 'Flughafen Zürich (ZRH)',
    to: 'Ischgl',
    distance: '~235 km',
    driveTime: '~2 Std. 30 Min.',
    routeDescription: 'Östlich über die Schweizer Autobahnen A3/A13, Einreise nach Österreich bei Feldkirch auf die S16/B188 ins Paznauntal.',
    whyBook: [
      'Exklusiver VIP-Transfer für grenzüberschreitende Ankünfte aus Zürich',
      'Erfahrene schweizerisch-österreichische Grenz-Chauffeure',
      'Diskretes und komfortables Executive-Reisen',
    ],
    crossBorder: true,
  },
  {
    slug: 'graz-to-ljubljana',
    from: 'Graz',
    to: 'Ljubljana',
    distance: '~195 km',
    driveTime: '~2 Std.',
    routeDescription: 'Südlich über die A2 Süd Autobahn durch den Grenzübergang Spielfeld nach Slowenien auf die Autobahn A1.',
    whyBook: [
      'Nahtlose regionale grenzüberschreitende Verbindung zwischen der Steiermark und Slowenien',
      'Ideal für Geschäftsreisen und diplomatische Fahrten',
      'Festpreis inklusive slowenischer Autobahnvignette',
    ],
    crossBorder: true,
  },
  {
    slug: 'graz-to-venice',
    from: 'Graz',
    to: 'Venedig',
    distance: '~380 km',
    driveTime: '~3 Std. 45 Min.',
    routeDescription: 'Südwestlich über die A2 Süd Autobahn, Grenzübertritt bei Tarvisio nach Italien auf die A23/A4 nach Venedig.',
    whyBook: [
      'Exklusiver privater Intercity-Transfer in die venezianische Lagune (Piazzale Roma)',
      'Komfortable Langstreckenfahrt in Mercedes-Limousine oder -Van',
      'Flexible Zwischenstopps in Kärnten oder Friaul möglich',
    ],
    crossBorder: true,
  },
  {
    slug: 'klagenfurt-to-ljubljana',
    from: 'Klagenfurt',
    to: 'Ljubljana',
    distance: '~85 km',
    driveTime: '~1 Std.',
    routeDescription: 'Südlich über die B91 Loiblpass-Straße oder die A11 durch den Karawankentunnel direkt nach Slowenien.',
    whyBook: [
      'Schnellster grenzüberschreitender Transfer zwischen Kärnten und Ljubljana',
      'Mautgebühren für den Karawankentunnel im Festpreis inbegriffen',
      'Tür-zu-Tür-Transfer für Hotel- und Geschäftstermine',
    ],
    crossBorder: true,
  },
  {
    slug: 'klagenfurt-to-venice',
    from: 'Klagenfurt',
    to: 'Venedig',
    distance: '~280 km',
    driveTime: '~2 Std. 45 Min.',
    routeDescription: 'Südwestlich über die A2 Süd Autobahn über die italienische Grenze bei Udine (A23) nach Venedig.',
    whyBook: [
      'Direkter Luxustransfer von den Alpen an die Adria',
      'Kein Zugumstieg mit schwerem Kreuzfahrt- oder Urlaubsgepäck',
      'Lizenziert für internationale Abholungen und Ablieferungen in Italien',
    ],
    crossBorder: true,
  },
  {
    slug: 'vienna-to-prague',
    from: 'Wien',
    to: 'Prag',
    distance: '~310 km',
    driveTime: '~3 Std. 15 Min.',
    routeDescription: 'Nördlich über die A5 Weinviertel Autobahn nach Tschechien über Mikulov auf der D52/D1 nach Prag.',
    whyBook: [
      'Erstklassiger Hauptstadt-zu-Hauptstadt-Transfer in Mitteleuropa',
      'Direkte Abholung an Wiener Hotels bis zur Prager Burg oder Altstadt',
      'Alle tschechischen Autobahnvignetten-Gebühren inbegriffen',
    ],
    crossBorder: true,
  },
  {
    slug: 'salzburg-to-graz',
    from: 'Salzburg',
    to: 'Graz',
    distance: '~280 km',
    driveTime: '~2 Std. 45 Min.',
    routeDescription: 'Südöstlich über die A10 Tauernautobahn und die A9 Pyhrn Autobahn durchs Ennstal.',
    whyBook: [
      'Verbindet Österreichs führende Festspielstadt mit der steirischen Landeshauptstadt',
      'Komfortabler Intercity-Transfer ohne Umsteigen im Regionalzug',
      'Festpreis inklusive Bergtunnel-Mautgebühren',
    ],
  },
  {
    slug: 'bregenz-to-zurich-airport',
    from: 'Bregenz',
    to: 'Flughafen Zürich (ZRH)',
    distance: '~120 km',
    driveTime: '~1 Std. 15 Min.',
    routeDescription: 'Westlich über die Schweizer Grenze (Höchst/St. Margrethen) auf der Schweizer Autobahn A1 nach Zürich-Kloten.',
    whyBook: [
      'Wichtigste Flughafenanbindung für Vorarlberger Privat- und Geschäftsreisende',
      'Grenzüberschreitender lizenzierter Fahrer, Schweizer Vignette inbegriffen',
      'Pünktliche Flughafentransfers mit Flugverfolgung',
    ],
    crossBorder: true,
  },
  {
    slug: 'innsbruck-to-zurich',
    from: 'Innsbruck',
    to: 'Zürich',
    distance: '~290 km',
    driveTime: '~3 Std.',
    routeDescription: 'Westlich über die A12/S16 durch den Arlberg, Grenzübertritt über Liechtenstein/Schweiz auf der A3 nach Zürich.',
    whyBook: [
      'Direkter Stadt-zu-Stadt-Transfer zwischen Tirol und dem Finanzplatz Zürich',
      'Komfortable Executive-Fahrt mit optionalen Zwischenstopps in Vaduz oder Bregenz',
      'Festpreis inklusive aller internationalen Transitgebühren',
    ],
    crossBorder: true,
  },
  {
    slug: 'vienna-to-wachau',
    from: 'Wien',
    to: 'Wachau-Tal',
    distance: '~85 km',
    driveTime: '~1 Std.',
    routeDescription: 'Westlich über die A1 und die S33 nach Krems und ins malerische Donau-Weinbaugebiet (Dürnstein/Melk).',
    whyBook: [
      'Privater Tagesausflugs- und Weinverkostungstransfer mit persönlichem Fahrer',
      'Flexibler Reiseplan mit Stopps bei Stift Melk und Weingütern',
      'Fester Tages- oder Transferpreis',
    ],
  },
  {
    slug: 'vienna-to-baden-wien',
    from: 'Wien',
    to: 'Baden bei Wien',
    distance: '~30 km',
    driveTime: '~35 Min.',
    routeDescription: 'Südlich über die A2 Süd Autobahn direkt in den Kurort Baden.',
    whyBook: [
      'Schneller Executive-Transfer zur Therme und zum Casino Baden',
      'Ideal für Hotelgäste, abendliche Casinobesuche und Wellness-Aufenthalte',
      'Festpreis, Tür zu Tür',
    ],
  },
  {
    slug: 'bregenz-to-lech',
    from: 'Bregenz',
    to: 'Lech am Arlberg',
    distance: '~95 km',
    driveTime: '~1 Std. 15 Min.',
    routeDescription: 'Südöstlich über die Rheintal Autobahn A14 und die B197 über den Flexenpass nach Lech.',
    whyBook: [
      'Direkte Verbindung vom Vorarlberger Rheintal zum Luxusresort am Arlberg',
      'Erfahrene Bergchauffeure für starke winterliche Schneefälle',
      'Geräumige Luxus-Vans der V-Klasse für Familien und Skiausrüstung',
    ],
  },
  {
    slug: 'bregenz-to-st-anton',
    from: 'Bregenz',
    to: 'St. Anton am Arlberg',
    distance: '~105 km',
    driveTime: '~1 Std. 20 Min.',
    routeDescription: 'Südöstlich über die A14 und die S16 Arlberg Schnellstraße nach St. Anton.',
    whyBook: [
      'Schneller, direkter Transfer zwischen dem Bodensee und dem Skigebiet Arlberg',
      'Alle Bergtunnel-Mautgebühren inbegriffen',
      'Festpreis mit professionellem Chauffeur',
    ],
  },
  {
    slug: 'linz-to-salzburg',
    from: 'Linz',
    to: 'Salzburg',
    distance: '~130 km',
    driveTime: '~1 Std. 25 Min.',
    routeDescription: 'Westlich auf der A1 Westautobahn, die Oberösterreich mit dem Land Salzburg verbindet.',
    whyBook: [
      'Häufig gebuchter Intercity-Transfer für Geschäfts- und Urlaubsreisende',
      'Kein Bahnhofsumstieg mit schwerem Gepäck nötig',
      'Direkt zum Hotel oder Anschluss an den Flughafen Linz/Salzburg',
    ],
  },
  {
    slug: 'villach-to-venice',
    from: 'Villach',
    to: 'Venedig',
    distance: '~240 km',
    driveTime: '~2 Std. 30 Min.',
    routeDescription: 'Südwestlich über die A2 Süd Autobahn über die italienische Grenze bei Tarvisio via Udine (A23/A4) nach Venedig.',
    whyBook: [
      'Kürzeste Luxus-Grenzfahrt von Kärnten an die venezianische Küste',
      'Direkte Ablieferung am Piazzale Roma oder Kreuzfahrtterminal Venedig',
      'Lizenziert für internationale Abholungen und Ablieferungen in Italien',
    ],
    crossBorder: true,
  },
  {
    slug: 'villach-to-ljubljana',
    from: 'Villach',
    to: 'Ljubljana',
    distance: '~100 km',
    driveTime: '~1 Std.',
    routeDescription: 'Südlich über die A11 durch den Karawankentunnel direkt nach Slowenien nach Ljubljana.',
    whyBook: [
      'Schnellste grenzüberschreitende Verbindung zwischen Kärnten und Flughafen/Stadt Ljubljana',
      'Tunnelmaut und slowenische Autobahnvignette inbegriffen',
      'Rund um die Uhr als Privattransfer verfügbar',
    ],
    crossBorder: true,
  },
]
